import { expect, test, type Page } from '@playwright/test'

const fixture = '/tests/e2e/fixture/'
const toggle = (page: Page) => page.getByRole('checkbox', { name: 'Caffeine mode', exact: true })

test('caffeine mode is off by default and saves through the sidebar', async ({ page }) => {
  await page.goto(fixture)
  const caffeine = toggle(page)
  await expect(caffeine).not.toBeChecked()
  await caffeine.check()
  await expect(caffeine).toBeChecked()
  await expect.poll(() => page.evaluate(async () => (await window.anvil.settings.get()).caffeineMode)).toBe(true)
  await caffeine.uncheck()
  await expect.poll(() => page.evaluate(async () => (await window.anvil.settings.get()).caffeineMode)).toBe(false)
})

test('pending caffeine write shows saving state and settles', async ({ page }) => {
  await page.goto(`${fixture}?settingsControlled`)
  const caffeine = toggle(page)
  await caffeine.check()
  await expect(page.getByText('Saving Caffeine mode…', { exact: true })).toHaveCount(0)
  expect(await page.evaluate(() => window.settingsTest.calls)).toEqual([{ caffeineMode: true }])
  expect(await page.evaluate(async () => (await window.anvil.settings.get()).caffeineMode)).toBe(false)
  await page.evaluate(() => window.settingsTest.release())
  await expect(page.getByText('Saving Caffeine mode…', { exact: true })).toBeHidden()
  await expect(caffeine).toBeChecked()
  expect(await page.evaluate(async () => (await window.anvil.settings.get()).caffeineMode)).toBe(true)
})

test('failed caffeine write restores confirmed value and retries', async ({ page }) => {
  await page.goto(`${fixture}?settingsControlled`)
  const caffeine = toggle(page)
  await caffeine.check()
  await page.evaluate(() => window.settingsTest.release(true))
  await expect(caffeine).not.toBeChecked()
  await expect(page.getByRole('alert')).toContainText('Could not save Caffeine mode')
  expect(await page.evaluate(async () => (await window.anvil.settings.get()).caffeineMode)).toBe(false)
  await page.getByRole('button', { name: 'Retry', exact: true }).click()
  await expect(caffeine).toBeChecked()
  await page.evaluate(() => window.settingsTest.release())
  await expect(page.getByRole('alert')).toBeHidden()
  expect(await page.evaluate(async () => (await window.anvil.settings.get()).caffeineMode)).toBe(true)

  // A failed disable must restore true, and retry must send false.
  await caffeine.uncheck()
  await page.evaluate(() => window.settingsTest.release(true))
  await expect(caffeine).toBeChecked()
  await expect(page.getByRole('alert')).toBeVisible()
  await page.getByRole('button', { name: 'Retry', exact: true }).click()
  await page.evaluate(() => window.settingsTest.release())
  await expect(caffeine).not.toBeChecked()
  expect(await page.evaluate(async () => (await window.anvil.settings.get()).caffeineMode)).toBe(false)
})

test('rapid toggles cannot overwrite the latest choice', async ({ page }) => {
  await page.goto(`${fixture}?settingsControlled`)
  const caffeine = toggle(page)
  await caffeine.check()
  await caffeine.uncheck()
  await caffeine.check()
  expect(await page.evaluate(() => window.settingsTest.calls)).toEqual([{ caffeineMode: true }])
  await expect(caffeine).toBeChecked()
  await page.evaluate(() => window.settingsTest.release())
  await expect.poll(() => page.evaluate(() => window.settingsTest.calls.length)).toBe(2)
  await page.evaluate(() => window.settingsTest.release())
  await expect.poll(() => page.evaluate(() => window.settingsTest.calls.length)).toBe(3)
  await page.evaluate(() => window.settingsTest.release())
  await expect(page.getByText('Saving Caffeine mode…', { exact: true })).toBeHidden()
  expect(await page.evaluate(() => window.settingsTest.calls)).toEqual([
    { caffeineMode: true }, { caffeineMode: false }, { caffeineMode: true }
  ])
  expect(await page.evaluate(async () => (await window.anvil.settings.get()).caffeineMode)).toBe(true)
})

test('earlier rejected toggle does not replace the latest pending choice', async ({ page }) => {
  await page.goto(`${fixture}?settingsControlled`)
  const caffeine = toggle(page)
  await caffeine.check()
  await caffeine.uncheck()
  await page.evaluate(() => window.settingsTest.release(true))
  await expect.poll(() => page.evaluate(() => window.settingsTest.calls.length)).toBe(2)
  await expect(caffeine).not.toBeChecked()
  await expect(page.getByRole('alert')).not.toBeVisible()
  await expect(page.getByText('Saving Caffeine mode…', { exact: true })).toHaveCount(0)
  await page.evaluate(() => window.settingsTest.release())
  await expect(page.getByText('Saving Caffeine mode…', { exact: true })).toBeHidden()
  expect(await page.evaluate(async () => (await window.anvil.settings.get()).caffeineMode)).toBe(false)
})

test('caffeine autosave preserves other autosaved preferences', async ({ page }) => {
  await page.goto(fixture)
  await toggle(page).check()
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('navigation', { name: 'Settings sections' }).getByRole('button', { name: 'Source control', exact: true }).click()
  await page.getByLabel('Rebase mode').selectOption('agent')
  await expect(page.getByText('Saved', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => window.settingsTest.calls)).toEqual([{ caffeineMode: true }, { rebaseMode: 'agent' }])
  await page.getByRole('button', { name: 'Back to workspace', exact: true }).click()
  await expect(toggle(page)).toBeChecked()
  expect(await page.evaluate(async () => (await window.anvil.settings.get()).caffeineMode)).toBe(true)
  expect(await page.evaluate(async () => (await window.anvil.settings.get()).rebaseMode)).toBe('agent')
})

test('caffeine displays confirmed value when settings finish loading', async ({ page }) => {
  await page.goto(`${fixture}?settingsLoading`)
  await page.getByRole('button', { name: 'Back to workspace', exact: true }).click()
  const caffeine = toggle(page)
  await expect(caffeine).toBeDisabled()
  await page.evaluate(() => window.settingsTest.finishLoading())
  await expect(caffeine).toBeEnabled()
  await expect(caffeine).toBeChecked()
  expect(await page.evaluate(() => window.settingsTest.calls)).toEqual([])
})