import { expect, test } from '@playwright/test'
import { restoreComposerSelection } from './composer-setup'

test.beforeEach(async ({ page }) => restoreComposerSelection(page))

const fixture = '/tests/e2e/fixture/'

test('model picker filters by company and search, and omits reasoning when metadata is unavailable', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 900, height: 600 })
  await page.goto(fixture)
  await page.evaluate(() => {
    window.anvil.agents.models = async (agentId) => ({
      agentId,
      models: ['openai/gpt-5.4', 'openai/gpt-5-mini', 'anthropic/claude-sonnet-4-6', 'anthropic/claude-opus-4-6', 'google/gemini-2.5-pro']
    })
  })
  const composer = page.getByRole('form', { name: 'Start a task' })
  await composer.getByRole('button', { name: 'More task options', exact: true }).click()
  await composer.getByRole('combobox', { name: 'Agent', exact: true }).selectOption('opencode')
  await page.keyboard.press('Escape')
  await composer.getByRole('button', { name: 'Model: model', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Choose model' })
  const search = dialog.getByRole('searchbox', { name: 'Search models' })
  await expect(search).toBeFocused()
  await expect(dialog).toBeInViewport()
  const companies = dialog.getByRole('navigation', { name: 'Filter models by company' })
  await companies.getByRole('button', { name: 'Anthropic', exact: true }).click()
  await expect(companies.getByRole('button', { name: 'Anthropic', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(dialog.getByRole('button', { name: 'Claude Sonnet 4.6', exact: true })).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'GPT 5.4', exact: true })).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('model-picker.png') })
  await search.fill('opus')
  await expect(dialog.getByRole('button', { name: 'Claude Sonnet 4.6', exact: true })).toHaveCount(0)
  await search.press('ArrowDown')
  await expect(dialog.getByRole('button', { name: 'Claude Opus 4.6', exact: true })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(dialog).toHaveCount(0)
  const selectedModel = composer.getByRole('button', { name: 'Model: Claude Opus 4.6', exact: true })
  await expect(selectedModel).toBeFocused()
  await composer.getByRole('button', { name: 'More task options', exact: true }).click()
  await expect(composer.getByRole('combobox', { name: 'Thinking level', exact: true })).toBeDisabled()
  await expect(composer.getByRole('combobox', { name: 'Thinking level', exact: true }).locator('option:checked')).toHaveText('Agent default')
  await page.keyboard.press('Escape')
  await page.screenshot({ path: testInfo.outputPath('composer.png') })
  await composer.getByRole('textbox').fill('Build search')
  await composer.getByRole('button', { name: 'Send', exact: true }).click()
  await expect(page.getByRole('main').getByRole('heading', { name: 'Build search', exact: true })).toBeVisible()
  const startedTasks = await page.evaluate(async () => (await window.anvil.tasks.list()).filter((task) => task.id.startsWith('started-')))
  expect(startedTasks).toHaveLength(1)
  expect(startedTasks[0]).toMatchObject({ agentId: 'opencode', model: 'anthropic/claude-opus-4-6' })
  expect(startedTasks[0]).not.toHaveProperty('thinkingLevel')
})

test('creator filters group models by credential provider and preserve the selected route', async ({ page }, testInfo) => {
  await page.goto(fixture)
  await page.evaluate(() => {
    window.anvil.agents.models = async (agentId) => ({
      agentId,
      models: [
        'anthropic/claude-sonnet-4-6', 'openai/gpt-5.4', 'google/gemini-2.5-pro',
        'openrouter/anthropic/claude-sonnet-4-6', 'openrouter/openai/gpt-5.4',
        'openrouter/nvidia/nemotron-3-ultra-550b-a55b:free',
        'opencode/claude-sonnet-4-6', 'opencode-go/gpt-5.4'
      ]
    })
  })
  const composer = page.getByRole('form', { name: 'Start a task' })
  await composer.getByRole('combobox', { name: 'Agent', exact: true }).selectOption('opencode')
  await composer.getByRole('button', { name: 'Model: model', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Choose model' })
  const companies = dialog.getByRole('navigation', { name: 'Filter models by company' })
  await expect(companies.getByRole('button', { name: 'OpenRouter', exact: true })).toHaveCount(0)
  await companies.getByRole('button', { name: 'Anthropic', exact: true }).click()
  const openrouter = dialog.getByRole('group', { name: 'OpenRouter models', exact: true })
  const zen = dialog.getByRole('group', { name: 'OpenCode Zen models', exact: true })
  await expect(zen.getByRole('button', { name: 'Claude Sonnet 4.6', exact: true })).toBeVisible()
  await expect(openrouter.getByRole('button', { name: 'Claude Sonnet 4.6', exact: true })).toBeVisible()
  const artwork = openrouter.locator('span[aria-hidden="true"]').first()
  await expect(artwork).toHaveCSS('mask-image', /openrouter\.svg/)
  expect(await artwork.evaluate(async (element) => {
    const image = new Image()
    image.src = getComputedStyle(element).maskImage.slice(5, -2)
    await image.decode()
    return image.naturalWidth
  })).toBe(512)
  await expect(openrouter.getByRole('button')).toContainText('OpenRouter credentials')
  await expect(zen.getByRole('button')).toContainText('OpenCode Zen credentials')
  await companies.getByRole('button', { name: 'OpenAI', exact: true }).click()
  const go = dialog.getByRole('group', { name: 'OpenCode Go models', exact: true })
  await expect(go.getByRole('button', { name: 'GPT 5.4', exact: true })).toHaveAttribute('title', 'opencode-go/gpt-5.4')
  await expect(openrouter.getByRole('button', { name: 'GPT 5.4', exact: true })).toHaveAttribute('title', 'openrouter/openai/gpt-5.4')
  await expect(go.getByRole('button')).toContainText('OpenCode Go credentials')
  await page.screenshot({ path: testInfo.outputPath('openrouter-provider-groups.png') })
  await companies.getByRole('button', { name: 'All companies', exact: true }).click()
  const search = dialog.getByRole('searchbox')
  await search.fill('claude')
  const models = dialog.getByRole('group', { name: 'Models', exact: true }).getByRole('button')
  await expect(models).toHaveCount(3)
  await expect(openrouter.getByRole('button')).toHaveAccessibleDescription('Uses OpenRouter credentials')
  await page.screenshot({ path: testInfo.outputPath('openrouter-search.png') })
  await search.fill('openrouter')
  await expect(models).toHaveCount(3)
  await expect(zen).toHaveCount(0)
  await search.fill('OpenCode Go')
  await expect(models).toHaveCount(1)
  await expect(models).toHaveAttribute('title', 'opencode-go/gpt-5.4')
  await search.fill('claude')
  await openrouter.getByRole('button', { name: 'Claude Sonnet 4.6', exact: true }).click()
  const selected = composer.getByRole('button', { name: 'Model: Claude Sonnet 4.6', exact: true })
  await expect(selected).toHaveAttribute('title', 'Claude Sonnet 4.6 · OpenRouter credentials')
  await selected.click()
  await dialog.getByRole('navigation').getByRole('button', { name: 'Anthropic', exact: true }).click()
  await expect(openrouter.getByRole('button', { name: 'Claude Sonnet 4.6', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.keyboard.press('Escape')
  await composer.getByRole('textbox').fill('Use OpenRouter for this task')
  await composer.getByRole('button', { name: 'Send', exact: true }).click()
  await expect(page.getByRole('main').getByRole('heading', { name: 'Use OpenRouter for this task', exact: true })).toBeVisible()
  const startedTasks = await page.evaluate(async () => (await window.anvil.tasks.list()).filter((task) => task.id.startsWith('started-')))
  expect(startedTasks).toHaveLength(1)
  expect(startedTasks[0]).toMatchObject({ agentId: 'opencode', model: 'openrouter/anthropic/claude-sonnet-4-6' })
})

test('picker dismisses with Escape or outside click without changing the model or draft', async ({ page }) => {
  await page.goto(fixture)
  const composer = page.getByRole('form', { name: 'Start a task' })
  await composer.getByRole('textbox').fill('Keep this draft')
  const trigger = composer.getByRole('button', { name: 'Model: GPT 5', exact: true })
  await trigger.click()
  const dialog = page.getByRole('dialog', { name: 'Choose model' })
  await dialog.getByRole('searchbox').fill('no such model')
  await expect(dialog.getByRole('status')).toHaveText('No models match your search.')
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(trigger).toBeFocused()
  await trigger.click()
  await expect(dialog.getByRole('searchbox')).toHaveValue('')
  await page.mouse.click(5, 5)
  await expect(dialog).toHaveCount(0)
  await expect(trigger).toBeFocused()
  await expect(composer.getByRole('textbox')).toHaveValue('Keep this draft')
})

test('unavailable catalogues preserve the saved model and allow custom models without an implicit default', async ({ page }) => {
  await page.goto(fixture)
  await page.evaluate(() => {
    window.anvil.agents.models = async (agentId) => ({ agentId, models: [], error: 'Provider unavailable' })
  })
  const composer = page.getByRole('form', { name: 'Start a task' })
  await composer.getByRole('combobox', { name: 'Agent', exact: true }).selectOption('opencode')
  await composer.getByRole('button', { name: 'Model: model', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Choose model' })
  await expect(dialog.getByRole('button', { name: 'model', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(dialog.getByRole('status')).toHaveText('Could not list models: Provider unavailable')
  await dialog.getByRole('textbox', { name: 'Custom model' }).fill('openai/gpt-5.4')
  await dialog.getByRole('button', { name: 'Use custom model' }).click()
  await composer.getByRole('button', { name: 'Model: GPT 5.4', exact: true }).click()
  await expect(dialog.getByRole('button', { name: 'Agent default', exact: true })).toHaveCount(0)
  await expect(dialog.getByRole('button', { name: 'GPT 5.4', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.keyboard.press('Escape')
  await page.reload()
  await expect(composer.getByRole('button', { name: 'Model: GPT 5.4', exact: true })).toBeVisible()
})

test('picker fits a narrow, short viewport and traps keyboard focus', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 600, height: 480 })
  await page.goto(fixture)
  await page.getByRole('button', { name: 'Model: GPT 5', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Choose model' })
  await expect(dialog).toBeInViewport()
  for (let index = 0; index < 12; index++) {
    await page.keyboard.press('Tab')
    expect(await dialog.evaluate((element) => element.contains(document.activeElement))).toBe(true)
  }
  await page.screenshot({ path: testInfo.outputPath('model-picker-narrow.png') })
})
