import { expect, test } from '@playwright/test'
import { chooseProvider, restoreComposerSelection } from './composer-setup'

test.beforeEach(async ({ page }) => restoreComposerSelection(page))

const fixture = '/tests/e2e/fixture/'

test('model picker searches by company and model name, and omits reasoning when metadata is unavailable', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 900, height: 600 })
  await page.goto(fixture)
  await page.evaluate(() => {
    window.anvil.agents.models = async (agentId) => ({
      agentId,
      models: ['openai/gpt-5.4', 'openai/gpt-5-mini', 'anthropic/claude-sonnet-4-6', 'anthropic/claude-opus-4-6', 'google/gemini-2.5-pro']
    })
  })
  const composer = page.getByRole('form', { name: 'Start a task' })
  await chooseProvider(composer.getByRole('button', { name: /^(Choose a model|Model:)/ }), 'opencode')
  await composer.getByRole('button', { name: 'Model: model', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Choose model' })
  const search = dialog.getByRole('searchbox', { name: 'Search models' })
  await expect(search).toBeFocused()
  await expect(dialog).toBeInViewport()
  await search.fill('Anthropic')
  await expect(dialog.getByRole('button', { name: 'Claude Sonnet 4.6', exact: true })).toBeVisible()
  await expect(dialog.getByRole('button', { name: 'GPT 5.4', exact: true })).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('model-picker.png') })
  await search.fill('opus')
  await expect(dialog.getByRole('button', { name: 'Claude Sonnet 4.6', exact: true })).toHaveCount(0)
  await search.press('ArrowDown')
  await expect(dialog.getByRole('button', { name: 'Claude Opus 4.6', exact: true })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(dialog).toHaveCount(0)
  const selectedModel = composer.getByRole('button', { name: 'Model: Claude Opus 4.6', exact: true })
  await expect(selectedModel).toBeFocused()
  await composer.getByRole('button', { name: 'More task options', exact: true }).click()
  await expect(composer.getByRole('combobox', { name: 'Reasoning effort', exact: true })).toBeDisabled()
  await expect(composer.getByRole('combobox', { name: 'Reasoning effort', exact: true }).locator('option:checked')).toHaveText('Reasoning unavailable')
  await page.keyboard.press('Escape')
  await page.screenshot({ path: testInfo.outputPath('composer.png') })
  await composer.getByRole('textbox').fill('Build search')
  await composer.getByRole('button', { name: 'Send', exact: true }).click()
  await expect(page.getByRole('main').getByRole('heading', { name: 'Build search', exact: true })).toBeVisible()
  const startedTasks = await page.evaluate(async () => (await window.anvil.tasks.list()).filter((task) => task.id.startsWith('started-')))
  expect(startedTasks).toHaveLength(1)
  expect(startedTasks[0]).toMatchObject({ agentId: 'opencode', model: 'anthropic/claude-opus-4-6' })
  expect(startedTasks[0]).not.toHaveProperty('reasoningEffort')
})

test('search preserves credential groups and the selected model route', async ({ page }, testInfo) => {
  await page.goto(fixture)
  await page.evaluate(() => {
    window.anvil.agents.models = async (agentId) => ({
      agentId,
      models: [
        'anthropic/claude-sonnet-4-6', 'openai/gpt-5.4', 'google/gemini-2.5-pro',
        'openrouter/anthropic/claude-sonnet-4-6', 'openrouter/openai/gpt-5.4',
        'openrouter/nvidia/nemotron-3-ultra-550b-a55b:free',
        'opencode/claude-sonnet-4-6', 'opencode-go/gpt-5.4'
      ]
    })
  })
  const composer = page.getByRole('form', { name: 'Start a task' })
  await chooseProvider(composer.getByRole('button', { name: /^(Choose a model|Model:)/ }), 'opencode')
  await composer.getByRole('button', { name: 'Model: model', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Choose model' })
  const search = dialog.getByRole('searchbox', { name: 'Search models' })
  await search.fill('Anthropic')
  const openrouter = dialog.getByRole('group', { name: 'OpenRouter models', exact: true })
  const zen = dialog.getByRole('group', { name: 'OpenCode Zen models', exact: true })
  await expect(zen.getByRole('button', { name: 'Claude Sonnet 4.6', exact: true })).toBeVisible()
  await expect(openrouter.getByRole('button', { name: 'Claude Sonnet 4.6', exact: true })).toBeVisible()
  await expect(openrouter.getByRole('button')).toHaveAccessibleDescription('Uses OpenRouter credentials')
  await expect(zen.getByRole('button')).toHaveAccessibleDescription('Uses OpenCode Zen credentials')
  await search.fill('OpenAI')
  const go = dialog.getByRole('group', { name: 'OpenCode Go models', exact: true })
  await expect(go.getByRole('button', { name: 'GPT 5.4', exact: true })).toHaveAttribute('title', 'opencode-go/gpt-5.4')
  await expect(openrouter.getByRole('button', { name: 'GPT 5.4', exact: true })).toHaveAttribute('title', 'openrouter/openai/gpt-5.4')
  await expect(go.getByRole('button')).toHaveAccessibleDescription('Uses OpenCode Go credentials')
  await page.screenshot({ path: testInfo.outputPath('openrouter-provider-groups.png') })
  await search.fill('claude')
  const models = dialog.getByRole('group', { name: 'Models', exact: true }).getByRole('button')
  await expect(models).toHaveCount(3)
  await expect(openrouter.getByRole('button')).toHaveAccessibleDescription('Uses OpenRouter credentials')
  await page.screenshot({ path: testInfo.outputPath('openrouter-search.png') })
  await search.fill('openrouter')
  await expect(models).toHaveCount(3)
  await expect(zen).toHaveCount(0)
  await search.fill('OpenCode Go')
  await expect(models).toHaveCount(1)
  await expect(models).toHaveAttribute('title', 'opencode-go/gpt-5.4')
  await search.fill('claude')
  await openrouter.getByRole('button', { name: 'Claude Sonnet 4.6', exact: true }).click()
  const selected = composer.getByRole('button', { name: 'Model: Claude Sonnet 4.6', exact: true })
  await expect(selected).toHaveAttribute('title', 'OpenCode · Claude Sonnet 4.6 · OpenRouter credentials')
  await selected.click()
  await search.fill('Anthropic')
  await expect(openrouter.getByRole('button', { name: 'Claude Sonnet 4.6', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.keyboard.press('Escape')
  await composer.getByRole('textbox').fill('Use OpenRouter for this task')
  await composer.getByRole('button', { name: 'Send', exact: true }).click()
  await expect(page.getByRole('main').getByRole('heading', { name: 'Use OpenRouter for this task', exact: true })).toBeVisible()
  const startedTasks = await page.evaluate(async () => (await window.anvil.tasks.list()).filter((task) => task.id.startsWith('started-')))
  expect(startedTasks).toHaveLength(1)
  expect(startedTasks[0]).toMatchObject({ agentId: 'opencode', model: 'openrouter/anthropic/claude-sonnet-4-6' })
})

test('picker dismisses with Escape or outside click without changing the model or draft', async ({ page }) => {
  await page.goto(fixture)
  const composer = page.getByRole('form', { name: 'Start a task' })
  await composer.getByRole('textbox').fill('Keep this draft')
  const trigger = composer.getByRole('button', { name: 'Model: GPT 5', exact: true })
  await trigger.click()
  const dialog = page.getByRole('dialog', { name: 'Choose model' })
  await dialog.getByRole('searchbox').fill('no such model')
  await expect(dialog.getByRole('status')).toHaveText('No models match your search.')
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(trigger).toBeFocused()
  await trigger.click()
  await expect(dialog.getByRole('searchbox')).toHaveValue('')
  await page.mouse.click(5, 5)
  await expect(dialog).toHaveCount(0)
  await expect(trigger).toBeFocused()
  await expect(composer.getByRole('textbox')).toHaveValue('Keep this draft')
})

test('unavailable catalogues preserve the saved model and allow custom models without an implicit default', async ({ page }) => {
  await page.goto(fixture)
  await page.evaluate(() => {
    window.anvil.agents.models = async (agentId) => ({ agentId, models: [], error: 'Provider unavailable' })
  })
  const composer = page.getByRole('form', { name: 'Start a task' })
  await chooseProvider(composer.getByRole('button', { name: /^(Choose a model|Model:)/ }), 'opencode')
  await composer.getByRole('button', { name: 'Model: model', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Choose model' })
  await expect(dialog.getByRole('button', { name: 'model', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(dialog.getByRole('status')).toHaveText('Could not list models: Provider unavailable')
  await dialog.getByRole('textbox', { name: 'Custom model' }).fill('openai/gpt-5.4')
  await dialog.getByRole('button', { name: 'Use custom model' }).click()
  await composer.getByRole('button', { name: 'Model: GPT 5.4', exact: true }).click()
  await expect(dialog.getByRole('button', { name: 'Agent default', exact: true })).toHaveCount(0)
  await expect(dialog.getByRole('button', { name: 'GPT 5.4', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.keyboard.press('Escape')
  await page.reload()
  await expect(composer.getByRole('button', { name: 'Model: GPT 5.4', exact: true })).toBeVisible()
})

test('picker fits a narrow, short viewport and traps keyboard focus', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 600, height: 480 })
  await page.goto(fixture)
  await page.getByRole('button', { name: 'Model: GPT 5', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Choose model' })
  await expect(dialog).toBeInViewport()
  for (let index = 0; index < 12; index++) {
    await page.keyboard.press('Tab')
    expect(await dialog.evaluate((element) => element.contains(document.activeElement))).toBe(true)
  }
  await page.screenshot({ path: testInfo.outputPath('model-picker-narrow.png') })
})

test('providers stay beside scrollable models, support keyboard navigation, and cancel without changing selection', async ({ page }, testInfo) => {
  await page.goto(fixture)
  const trigger = page.getByRole('button', { name: 'Model: GPT 5', exact: true })
  await trigger.click()
  const dialog = page.getByRole('dialog', { name: 'Choose model', exact: true })
  const search = dialog.getByRole('searchbox', { name: 'Search models' })
  const providers = dialog.getByRole('navigation', { name: 'Providers' })
  const codex = providers.getByRole('button', { name: 'Codex', exact: true })
  const opencode = providers.getByRole('button', { name: 'OpenCode', exact: true })
  await expect(search).toBeFocused()
  await expect(codex).toHaveAttribute('aria-pressed', 'true')
  await codex.focus()
  await codex.press('ArrowDown')
  await expect(opencode).toBeFocused()
  await opencode.press('Enter')
  await expect(dialog).toBeVisible()
  await expect(opencode).toHaveAttribute('aria-pressed', 'true')
  const list = dialog.getByRole('group', { name: 'Models', exact: true })
  await expect(list.getByRole('button', { name: 'model', exact: true })).toBeVisible()
  const left = (await providers.boundingBox())!
  expect((await list.boundingBox())!.x).toBeGreaterThanOrEqual(left.x + left.width)
  await opencode.press('ArrowRight')
  await expect(search).toBeFocused()
  await search.press('ArrowDown')
  await page.keyboard.press('Enter')
  await expect(dialog).toHaveCount(0)
  const selected = page.getByRole('button', { name: 'Model: model', exact: true })
  await expect(selected).toHaveAccessibleDescription('OpenCode')
  await expect(selected).toBeFocused()
  await selected.click()
  await codex.click()
  await page.screenshot({ path: testInfo.outputPath('unified-picker-wide.png') })
  await page.mouse.click(5, 5)
  await expect(dialog).toHaveCount(0)
  await expect(selected).toHaveAccessibleDescription('OpenCode')
  await expect(selected).toBeFocused()
})

test('Escape dismisses the unified picker and returns focus to its trigger', async ({ page }, testInfo) => {
  await page.goto(fixture)
  const composer = page.getByRole('form', { name: 'Start a task' })
  await composer.getByRole('textbox', { name: 'Task prompt' }).fill('Keep the draft')
  const more = composer.getByRole('button', { name: 'More task options', exact: true })
  const provider = composer.getByRole('button', { name: /^(Choose a model|Model:)/ })
  await provider.click()
  const picker = page.getByRole('dialog', { name: 'Choose model', exact: true })
  await expect(picker.getByRole('searchbox')).toBeFocused()
  await expect(picker).toBeInViewport()
  await page.screenshot({ path: testInfo.outputPath('provider-picker-overview.png') })
  await page.keyboard.press('Escape')
  await expect(picker).toHaveCount(0)
  await expect(provider).toBeFocused()
  await more.click()
  await page.keyboard.press('Escape')
  await expect(more).toBeFocused()
  const branch = composer.getByRole('button', { name: 'Project branch', exact: true })
  await branch.click()
  await page.keyboard.press('Escape')
  await expect(branch).toBeFocused()
  const model = composer.getByRole('button', { name: 'Model: GPT 5', exact: true })
  await model.click()
  await page.mouse.click(5, 5)
  await expect(model).toBeFocused()
  await expect(composer.getByRole('textbox', { name: 'Task prompt' })).toHaveValue('Keep the draft')
})

test('late provider results stay in their own list and long catalogues scroll beside the provider column', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 600, height: 480 })
  await page.goto(fixture)
  await page.evaluate(() => {
    const originalModels = window.anvil.agents.models
    window.anvil.agents.models = async (agentId) => {
      if (agentId !== 'opencode') return originalModels(agentId)
      await new Promise<void>((resolve) => window.addEventListener('fixture:models-ready', () => resolve(), { once: true }))
      return { agentId, models: Array.from({ length: 100 }, (_, index) => `openrouter/company/model-${index}`) }
    }
  })
  const trigger = page.getByRole('button', { name: 'Model: GPT 5', exact: true })
  await trigger.click()
  const dialog = page.getByRole('dialog', { name: 'Choose model' })
  const providers = dialog.getByRole('navigation', { name: 'Providers' })
  const models = dialog.getByRole('group', { name: 'Models', exact: true })
  await providers.getByRole('button', { name: 'OpenCode', exact: true }).click()
  await expect(models).toHaveAttribute('aria-busy', 'true')
  await providers.getByRole('button', { name: 'Codex', exact: true }).click()
  await page.evaluate(() => window.dispatchEvent(new Event('fixture:models-ready')))
  await expect(models.getByRole('button', { name: 'GPT 5', exact: true })).toBeVisible()
  await expect(models.getByRole('button', { name: 'model-99', exact: true })).toHaveCount(0)
  await dialog.getByRole('searchbox').fill('GPT')
  await providers.getByRole('button', { name: 'OpenCode', exact: true }).click()
  await expect(dialog.getByRole('searchbox')).toHaveValue('')
  await expect(models.getByRole('button')).toHaveCount(101)
  const providerBounds = await providers.boundingBox()
  await dialog.getByRole('searchbox').press('ArrowDown')
  await page.keyboard.press('End')
  const last = models.getByRole('button').last()
  await expect(last).toBeFocused()
  await expect(last).toBeInViewport()
  expect(await models.evaluate((element) => element.scrollTop)).toBeGreaterThan(0)
  expect(await providers.boundingBox()).toEqual(providerBounds)
  expect(await dialog.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('unified-picker-scroll.png') })
  await page.keyboard.press('Escape')
  await expect(trigger).toHaveAccessibleDescription('Codex')
})
