import { expect, test, type Page } from '@playwright/test'
import { restoreComposerSelection } from './composer-setup'

const prompt = (page: Page) => page.getByRole('textbox', { name: 'Task prompt' })
const options = (page: Page) => page.getByRole('listbox', { name: 'Project files' }).getByRole('option')

test.beforeEach(async ({ page }) => {
  await restoreComposerSelection(page)
  await page.goto('/tests/e2e/fixture/')
  await expect(prompt(page)).toBeVisible()
})

test('ranks fuzzy filename and path matches, bounds results, and keeps textarea focus', async ({ page }) => {
  await prompt(page).fill('@tskc')
  await expect(options(page)).toHaveText(['src/TaskComposer.tsx', 'src/TaskCompletion.ts'])
  await expect(prompt(page)).toBeFocused()
  await prompt(page).fill('@srcmainidx')
  await expect(options(page).first()).toHaveText('src/main/index.ts')
  await prompt(page).press('Escape')
  await page.evaluate(() => { window.fileMentionTest.paths['project-0'] = Array.from({ length: 5000 }, (_, i) => `src/File${i}.ts`) })
  await prompt(page).fill('@File')
  await expect(page.getByRole('listbox', { name: 'Project files' }).getByRole('option')).toHaveCount(30)
})

test('replaces only the active range in the middle, restores caret, supports multiple paths and duplicate basenames', async ({ page }) => {
  await prompt(page).fill('Before @tskcpsr after')
  for (let index = 0; index < 6; index += 1) await prompt(page).press('ArrowLeft')
  await expect(options(page).first()).toHaveText('src/TaskComposer.tsx')
  await prompt(page).press('Enter')
  await expect(prompt(page)).toHaveValue('Before @"src/TaskComposer.tsx"  after')
  await prompt(page).pressSequentially('and @index')
  await expect(options(page).filter({ hasText: 'src/main/index.ts' })).toBeVisible()
  await expect(options(page).filter({ hasText: 'src/renderer/index.ts' })).toBeVisible()
  await options(page).filter({ hasText: 'src/renderer/index.ts' }).click()
  await expect(prompt(page)).toBeFocused()
  await expect(prompt(page)).toHaveValue('Before @"src/TaskComposer.tsx" and @"src/renderer/index.ts"  after')
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await expect.poll(() => page.evaluate(() => window.composerTest.starts.length)).toBe(1)
  const input = await page.evaluate(() => window.composerTest.starts[0])
  expect(input.fileReferences).toEqual(['src/TaskComposer.tsx', 'src/renderer/index.ts'])
  expect(input.prompt).toBe('Before @"src/TaskComposer.tsx" and @"src/renderer/index.ts"  after')
  expect(Object.keys(input).sort()).toEqual(['agentId', 'fileReferences', 'model', 'projectId', 'prompt', 'reasoningEffort', 'workspaceId'])
})

test('quotes spaces, Unicode and escaped filenames; editing and removing references updates payload', async ({ page }) => {
  await page.evaluate(() => { window.fileMentionTest.paths['project-0'].push('docs/a"b\\c.md') })
  await prompt(page).fill('@日本語')
  await options(page).filter({ hasText: 'docs/My notes 日本語.md' }).click()
  await prompt(page).pressSequentially('@abc')
  await options(page).filter({ hasText: 'docs/a"b\\c.md' }).click()
  await expect(prompt(page)).toHaveValue('@"docs/My notes 日本語.md" @"docs/a\\"b\\\\c.md" ')
  await prompt(page).fill('Keep @"docs/My notes 日本語.md" and edit @"docs/changed.md"')
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await expect.poll(() => page.evaluate(() => window.composerTest.starts[0]?.fileReferences)).toEqual(['docs/My notes 日本語.md'])
})

test('ignores email addresses and preserves multiline editing', async ({ page }) => {
  await prompt(page).fill('Email developer@example.com')
  await expect(page.getByRole('listbox', { name: 'Project files' })).toHaveCount(0)
  await prompt(page).press('Shift+Enter')
  await prompt(page).pressSequentially('Next line')
  await expect(prompt(page)).toHaveValue('Email developer@example.com\nNext line')
  expect(await page.evaluate(() => window.composerTest.starts)).toEqual([])
})

test('arrows and Enter select; Escape dismisses without closing NewTaskModal or submitting', async ({ page }) => {
  await page.evaluate(() => window.composerTest.openModal())
  const dialog = page.getByRole('dialog', { name: 'Start new task' })
  await prompt(page).fill('@index')
  const list = page.getByRole('listbox', { name: 'Project files' })
  await expect(list.getByRole('option')).toHaveCount(2)
  await prompt(page).press('ArrowUp')
  await expect(list.getByRole('option').last()).toHaveAttribute('aria-selected', 'true')
  await prompt(page).press('ArrowDown')
  await expect(list.getByRole('option').first()).toHaveAttribute('aria-selected', 'true')
  await prompt(page).press('Control+Enter')
  await expect(list).toHaveCount(0)
  expect(await page.evaluate(() => window.composerTest.starts)).toEqual([])
  await prompt(page).pressSequentially('@no-such-file')
  await expect(page.getByText('No matching files.')).toBeVisible()
  await prompt(page).press('Enter')
  await expect(dialog).toBeVisible()
  await prompt(page).press('Escape')
  await expect(list).toHaveCount(0)
  await expect(dialog).toBeVisible()
  await prompt(page).press('Escape')
  await expect(dialog).toHaveCount(0)
})

test('shows loading/errors and retries a fresh listing', async ({ page }) => {
  await page.evaluate(() => { window.fileMentionTest.delay['project-0'] = 400; window.fileMentionTest.error = 'Cannot list project' })
  await prompt(page).fill('@')
  await expect(page.getByText('Loading project files…')).toBeVisible()
  await prompt(page).press('Control+Enter')
  expect(await page.evaluate(() => window.composerTest.starts)).toEqual([])
  await expect(page.getByRole('alert')).toHaveText('Cannot list project')
  await page.evaluate(() => { window.fileMentionTest.error = null })
  await page.getByRole('button', { name: 'Refresh', exact: true }).click()
  await expect(options(page).filter({ hasText: 'new-untracked.txt' })).toBeVisible()
  await expect(prompt(page)).toBeFocused()
})

test('project switches clear references and ignore stale responses', async ({ page }) => {
  await prompt(page).fill('@tskcpsr')
  await options(page).first().click()
  await page.evaluate(() => { window.fileMentionTest.delay['project-0'] = 800 })
  await prompt(page).pressSequentially('@')
  await expect(page.getByText('Loading project files…')).toBeVisible()
  await page.evaluate(() => window.composerTest.selectProject('project-1'))
  await expect(prompt(page)).toHaveValue('')
  await prompt(page).fill('@Only')
  await expect(options(page).first()).toHaveText('workbench/OnlyHere.ts')
  await page.waitForTimeout(900)
  await expect(options(page).first()).toHaveText('workbench/OnlyHere.ts')
  await prompt(page).press('Enter')
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await expect.poll(() => page.evaluate(() => window.composerTest.starts[0]?.fileReferences)).toEqual(['workbench/OnlyHere.ts'])
  expect(await page.evaluate(() => window.composerTest.starts[0].projectId)).toBe('project-1')
})

test('keeps a missing-file draft for correction before send', async ({ page }) => {
  await prompt(page).fill('@untracked')
  await options(page).first().click()
  await page.evaluate(() => { window.fileMentionTest.paths['project-0'] = [] })
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Referenced file is missing')
  await expect(prompt(page)).toHaveValue('@"new-untracked.txt" ')
  expect(await page.evaluate(() => window.composerTest.starts)).toEqual([])
  await prompt(page).fill('Removed missing reference')
  await page.getByRole('button', { name: 'Send', exact: true }).click()
  await expect.poll(() => page.evaluate(() => window.composerTest.starts.length)).toBe(1)
  expect(await page.evaluate(() => window.composerTest.starts[0].fileReferences)).toBeUndefined()
})

test('IME confirmation and Escape do not select, submit or close the modal', async ({ page }) => {
  await page.evaluate(() => window.composerTest.openModal())
  await prompt(page).fill('@index')
  await expect(page.getByRole('listbox', { name: 'Project files' })).toBeVisible()
  await prompt(page).evaluate((element) => {
    element.dispatchEvent(new CompositionEvent('compositionstart', { bubbles: true }))
    element.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', ctrlKey: true, isComposing: true, bubbles: true }))
    element.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', isComposing: true, bubbles: true }))
  })
  await expect(prompt(page)).toHaveValue('@index')
  await expect(page.getByRole('dialog', { name: 'Start new task' })).toBeVisible()
  expect(await page.evaluate(() => window.composerTest.starts)).toEqual([])
  await prompt(page).evaluate((element) => element.dispatchEvent(new CompositionEvent('compositionend', { bubbles: true })))
  await expect(page.getByRole('listbox', { name: 'Project files' })).toBeVisible()
})
