import { expect, test } from '@playwright/test'

const fixture = '/tests/e2e/fixture/'

test('fresh composer asks for a provider and model and defaults thinking to Medium', async ({ page }, testInfo) => {
  await page.goto(fixture)
  const composer = page.getByRole('form', { name: 'Start a task' })
  const provider = composer.getByRole('combobox', { name: 'Agent', exact: true })
  await expect(provider).toHaveValue('')
  await expect(provider.locator('option:checked')).toHaveText('Choose a provider')
  await expect(composer.getByRole('combobox', { name: 'Thinking level' })).toHaveValue('Medium')
  const model = composer.getByRole('button', { name: 'Choose a Model', exact: true })
  await expect(model).toBeDisabled()
  await composer.getByRole('textbox').fill('Use my selected model')
  await expect(composer.getByRole('button', { name: 'Send', exact: true })).toBeDisabled()
  await page.screenshot({ path: testInfo.outputPath('composer-empty.png') })
  await provider.selectOption('codex')
  await expect(model).toBeEnabled()
  await expect(composer.getByRole('button', { name: 'Send', exact: true })).toBeDisabled()
  await composer.getByRole('textbox').press('Control+Enter')
  expect(await page.evaluate(async () => (await window.anvil.tasks.list()).filter((task) => task.id.startsWith('started-')))).toHaveLength(0)
  await model.click()
  await page.getByRole('dialog', { name: 'Choose model' }).getByRole('button', { name: 'GPT 5 Mini', exact: true }).click()
  await expect(composer.getByRole('button', { name: 'Send', exact: true })).toBeEnabled()
  await page.screenshot({ path: testInfo.outputPath('composer-selected.png') })
})

test('the last configuration survives provider switches, task submission, project switches, and reloads', async ({ page }) => {
  await page.goto(fixture)
  const composer = page.getByRole('form', { name: 'Start a task' })
  const provider = composer.getByRole('combobox', { name: 'Agent', exact: true })
  await provider.selectOption('codex')
  await composer.getByRole('button', { name: 'Choose a Model', exact: true }).click()
  await page.getByRole('dialog', { name: 'Choose model' }).getByRole('button', { name: 'GPT 5 Mini', exact: true }).click()
  await composer.getByRole('combobox', { name: 'Thinking level' }).selectOption('Extra high')
  await provider.selectOption('opencode')
  await composer.getByRole('button', { name: 'Choose a Model', exact: true }).click()
  await page.getByRole('dialog', { name: 'Choose model' }).getByRole('button', { name: 'model', exact: true }).click()
  await provider.selectOption('codex')
  await expect(composer.getByRole('button', { name: 'Model: GPT 5 Mini', exact: true })).toBeVisible()
  await composer.getByRole('textbox').fill('Keep my configuration')
  await composer.getByRole('button', { name: 'Send', exact: true }).click()
  await expect(page.getByRole('main').getByRole('heading', { name: 'Keep my configuration', exact: true })).toBeVisible()
  await page.keyboard.press('Control+n')
  await expect(provider).toHaveValue('codex')
  await expect(composer.getByRole('button', { name: 'Model: GPT 5 Mini', exact: true })).toBeVisible()
  await page.getByRole('navigation', { name: 'Filter tasks by project' }).getByRole('button', { name: 'Workbench', exact: true }).click()
  await expect(provider).toHaveValue('codex')
  await expect(composer.getByRole('combobox', { name: 'Thinking level' })).toHaveValue('Extra high')
  await page.reload()
  await expect(provider).toHaveValue('codex')
  await expect(composer.getByRole('button', { name: 'Model: GPT 5 Mini', exact: true })).toBeVisible()
  await expect(composer.getByRole('combobox', { name: 'Thinking level' })).toHaveValue('Extra high')
  await provider.selectOption('opencode')
  await expect(composer.getByRole('button', { name: 'Model: model', exact: true })).toBeVisible()
})

for (const saved of [
  'not valid JSON',
  JSON.stringify({ state: { agentId: 42, modelsByAgent: null, thinkingLevel: 'Invalid' }, version: 0 }),
  JSON.stringify({ state: { agentId: 'removed-provider', modelsByAgent: { codex: 42 }, thinkingLevel: null }, version: 0 })
]) {
  test(`invalid or unavailable saved configuration does not select a default provider: ${saved}`, async ({ page }) => {
    await page.addInitScript((saved) => localStorage.setItem('anvil-composer-preferences', saved), saved)
    await page.goto(fixture)
    const composer = page.getByRole('form', { name: 'Start a task' })
    const provider = composer.getByRole('combobox', { name: 'Agent', exact: true })
    await expect(provider).toHaveValue('')
    await expect(composer.getByRole('combobox', { name: 'Thinking level' })).toHaveValue('Medium')
    await expect(composer.getByRole('button', { name: 'Choose a Model', exact: true })).toBeDisabled()
    await provider.selectOption('codex')
    await expect(composer.getByRole('button', { name: 'Choose a Model', exact: true })).toBeEnabled()
  })
}

test('the new-task dialog shares the same saved configuration as the overview', async ({ page }) => {
  await page.goto(fixture)
  const overviewComposer = page.getByRole('main').getByRole('form', { name: 'Start a task' })
  await overviewComposer.getByRole('combobox', { name: 'Agent', exact: true }).selectOption('codex')
  await overviewComposer.getByRole('button', { name: 'Choose a Model', exact: true }).click()
  await page.getByRole('dialog', { name: 'Choose model' }).getByRole('button', { name: 'GPT 5 Mini', exact: true }).click()
  await page.getByRole('button', { name: 'New task', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Start new task', exact: true })
  await expect(dialog.getByRole('button', { name: 'Model: GPT 5 Mini', exact: true })).toBeVisible()
  await dialog.getByRole('button', { name: 'More task options', exact: true }).click()
  await expect(dialog.getByRole('combobox', { name: 'Agent', exact: true })).toHaveValue('codex')
  await dialog.getByRole('combobox', { name: 'Thinking level' }).selectOption('High')
  await page.keyboard.press('Escape')
  await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(overviewComposer.getByRole('combobox', { name: 'Thinking level' })).toHaveValue('High')
})
