import { expect, test } from '@playwright/test'

test('carousel bounds reads, supports keyboard selection and saves across reopening', async ({ page }) => {
  await page.goto('/tests/e2e/fixture/?wallpapers')
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('navigation', { name: 'Settings sections' }).getByRole('button', { name: 'Display', exact: true }).click()
  await page.getByRole('radio', { name: 'Image', exact: true }).check()
  await expect(page.getByRole('button', { name: 'image-0.png' })).toBeVisible()
  await expect.poll(() => page.evaluate(() => window.wallpaperTest.reads.length)).toBe(3)
  await page.getByRole('button', { name: 'Next images' }).click()
  const image = page.getByRole('button', { name: 'image-3.png' })
  await image.focus()
  await page.keyboard.press('Space')
  await expect(image).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Previous images' }).click()
  await expect(page.getByRole('button', { name: 'image-0.png' })).toBeVisible()
  await page.getByLabel('Background color', { exact: true }).fill('#abcdef')
  await expect(page.getByText('Saved', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('navigation', { name: 'Settings sections' }).getByRole('button', { name: 'Display', exact: true }).click()
  await expect(page.getByRole('radio', { name: 'Image', exact: true })).toBeChecked()
  await expect(page.getByLabel('Background color', { exact: true })).toHaveValue('#abcdef')
  await page.getByRole('button', { name: 'Next images' }).click()
  await expect(page.getByRole('button', { name: 'image-3.png' })).toHaveAttribute('aria-pressed', 'true')
})

test('failed autosave retains appearance after reopening and retry persists', async ({ page }) => {
  await page.goto('/tests/e2e/fixture/?wallpapers&settingsControlled')
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  const display = () => page.getByRole('navigation', { name: 'Settings sections' }).getByRole('button', { name: 'Display', exact: true }).click()
  await display()
  await page.getByRole('radio', { name: 'Image', exact: true }).check()
  await expect.poll(() => page.evaluate(() => window.settingsTest.calls.length)).toBe(1)
  await page.evaluate(() => window.settingsTest.release())
  await page.getByRole('button', { name: 'image-1.png' }).click()
  await expect.poll(() => page.evaluate(() => window.settingsTest.calls.length)).toBe(2)
  await page.evaluate(() => window.settingsTest.release(true))
  await expect(page.getByRole('alert')).toContainText('Could not save settings')
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await display()
  await expect(page.getByRole('button', { name: 'image-1.png' })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Retry', exact: true }).click()
  await expect.poll(() => page.evaluate(() => window.settingsTest.calls.length)).toBe(3)
  await page.evaluate(() => window.settingsTest.release())
  await expect(page.getByText('Saved', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => window.anvil.settings.get())).toMatchObject({ overviewWallpaperId: 'image-1.png', overviewBackgroundMode: 'image' })
})

test('reopening handles loading, empty, added, removed and unreadable images in a narrow window', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 390, height: 700 })
  await page.goto('/tests/e2e/fixture/')
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('navigation', { name: 'Settings sections' }).getByRole('button', { name: 'Display', exact: true }).click()
  await expect(page.getByRole('navigation', { name: 'Settings sections' })).toBeVisible()
  await expect(page.getByText('No wallpapers yet.', { exact: false })).toBeVisible()
  await page.getByRole('radio', { name: 'Image', exact: true }).check()
  await page.evaluate(() => {
    window.wallpaperTest.loading = true
    window.wallpaperTest.items = Array.from({ length: 7 }, (_, i) => ({ id: `${i}.png`, name: `${i}.png`, width: 1, height: 1 }))
  })
  await page.getByRole('navigation', { name: 'Settings sections' }).getByRole('button', { name: 'General', exact: true }).click()
  await page.getByRole('navigation', { name: 'Settings sections' }).getByRole('button', { name: 'Display', exact: true }).click()
  await expect(page.getByText('Loading wallpapers…')).toBeVisible()
  await page.evaluate(() => { window.wallpaperTest.loading = false })
  await page.getByRole('button', { name: '0.png', exact: true }).click()
  expect(await page.getByTestId('settings-page').evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('wallpaper-narrow.png') })
  await page.evaluate(() => { window.wallpaperTest.items = []; window.wallpaperTest.fail = true })
  await page.getByRole('navigation', { name: 'Settings sections' }).getByRole('button', { name: 'General', exact: true }).click()
  await page.getByRole('navigation', { name: 'Settings sections' }).getByRole('button', { name: 'Display', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Check folder permissions')
  await page.evaluate(() => { window.wallpaperTest.fail = false })
  await page.getByRole('navigation', { name: 'Settings sections' }).getByRole('button', { name: 'General', exact: true }).click()
  await page.getByRole('navigation', { name: 'Settings sections' }).getByRole('button', { name: 'Display', exact: true }).click()
  await expect(page.getByText('Selected image 0.png is unavailable.', { exact: false })).toBeVisible()
})

test('appearance initializes after delayed settings and solid color persists', async ({ page }) => {
  await page.goto('/tests/e2e/fixture/?settingsLoading&appearance&wallpapers')
  await page.getByRole('navigation', { name: 'Settings sections' }).getByRole('button', { name: 'Display', exact: true }).click()
  await expect(page.getByText('Loading settings…')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Save', exact: true })).toBeDisabled()
  expect(await page.evaluate(() => window.settingsTest.calls)).toEqual([])
  await page.evaluate(() => window.settingsTest.finishLoading())
  await expect(page.getByRole('radio', { name: 'Image', exact: true })).toBeChecked()
  await expect(page.getByLabel('Background color', { exact: true })).toHaveValue('#123456')
  await page.getByRole('radio', { name: 'Solid color', exact: true }).check()
  await expect(page.getByText('Saved', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Close', exact: true }).click()
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('navigation', { name: 'Settings sections' }).getByRole('button', { name: 'Display', exact: true }).click()
  await expect(page.getByRole('radio', { name: 'Solid color', exact: true })).toBeChecked()
  await page.getByRole('radio', { name: 'Image', exact: true }).check()
  await expect(page.getByRole('button', { name: 'image-0.png' })).toHaveAttribute('aria-pressed', 'true')
})
