import { expect, test } from '@playwright/test'

const fixture = '/tests/e2e/fixture/'

test('settings sidebar separates controls and retains drafts across sections', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1000, height: 780 })
  await page.goto(fixture)
  const prompt = page.getByRole('textbox', { name: 'Task prompt' })
  await prompt.fill('Keep my task draft')
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  const navigation = page.getByRole('navigation', { name: 'Settings sections' })
  await expect(navigation.getByRole('button')).toHaveText(['General', 'Providers', 'Source control', 'Keyboard shortcuts', 'Memory', 'Display'])
  await expect(page.getByRole('complementary', { name: 'Sidebar', exact: true }).getByRole('navigation')).toBeVisible()
  await expect(navigation.locator('svg[aria-hidden="true"]')).toHaveCount(6)
  await expect(navigation.getByRole('button', { name: 'General', exact: true })).toHaveAttribute('aria-current', 'page')
  await expect(prompt).toBeHidden()
  await navigation.getByRole('button', { name: 'Providers', exact: true }).click()
  await expect(page.getByLabel('Default agent')).toBeVisible()
  await navigation.getByRole('button', { name: 'Source control', exact: true }).click()
  await page.getByLabel('Rebase mode').selectOption('agent')
  await expect(page.getByRole('region', { name: 'GitHub integration' })).toBeVisible()
  await page.getByLabel('Personal access token').fill('fixture-unsaved-token')
  await navigation.getByRole('button', { name: 'Display', exact: true }).click()
  await page.getByLabel('Font size', { exact: true }).selectOption('18')
  await navigation.getByRole('button', { name: 'Source control', exact: true }).click()
  await expect(page.getByLabel('Personal access token')).toHaveValue('fixture-unsaved-token')
  await navigation.getByRole('button', { name: 'Display', exact: true }).click()
  // An external change must not be overwritten by an unrelated autosave.
  await page.evaluate(() => window.settingsTest.apply({ confirmRebase: false }))
  await expect(page.getByText('Saved', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Back to workspace', exact: true })).toBeInViewport()
  const settings = await page.evaluate(() => window.anvil.settings.get())
  expect(settings).toMatchObject({ fontSize: 18, rebaseMode: 'agent', confirmRebase: false })
  await page.screenshot({ path: testInfo.outputPath('settings-display.png') })
  await page.getByRole('button', { name: 'Back to workspace', exact: true }).click()
  await expect(prompt).toBeVisible()
  await expect(prompt).toHaveValue('Keep my task draft')
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await navigation.getByRole('button', { name: 'Display', exact: true }).click()
  await expect(page.getByLabel('Font size', { exact: true })).toHaveValue('18')
})

test('Command+, opens settings on macOS and shortcuts remain editable', async ({ page }, testInfo) => {
  await page.goto(`${fixture}?platform=darwin`)
  await expect(page.getByRole('button', { name: 'Settings', exact: true })).toBeVisible()
  await page.keyboard.press('Meta+,')
  const navigation = page.getByRole('navigation', { name: 'Settings sections' })
  await expect(navigation).toBeVisible()
  await navigation.getByRole('button', { name: 'Keyboard shortcuts', exact: true }).click()
  const shortcut = page.getByRole('button', { name: '⌘B', exact: true })
  await shortcut.click()
  await page.keyboard.press('Escape')
  await expect(navigation).toBeVisible()
  await shortcut.click()
  await page.keyboard.press('Meta+Shift+b')
  await expect(page.getByRole('button', { name: '⌘⇧B', exact: true })).toBeVisible()
  await expect.poll(() => page.evaluate(async () => (await window.anvil.settings.get()).keybindings.toggleSidebar)).toBe('Mod+Shift+B')
  await page.screenshot({ path: testInfo.outputPath('settings-shortcuts.png') })
  await page.getByRole('button', { name: 'Reset', exact: true }).click()
  await expect(shortcut).toBeVisible()
})

test('memory starts disabled and saves its model and Ollama URL', async ({ page }, testInfo) => {
  await page.goto(fixture)
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  const navigation = page.getByRole('navigation', { name: 'Settings sections' })
  await navigation.getByRole('button', { name: 'Memory', exact: true }).click()
  const toggle = page.getByRole('checkbox', { name: /Enable project memory/ })
  await expect(toggle).not.toBeChecked()
  await expect(page.getByLabel('Embedding model', { exact: true })).toHaveCount(0)
  await expect(page.getByLabel('Ollama base URL', { exact: true })).toHaveCount(0)
  await toggle.check()
  await expect(page.getByLabel('Embedding model', { exact: true })).toHaveValue('mxbai-embed-large')
  await expect(page.getByLabel('Ollama base URL', { exact: true })).toHaveValue('http://localhost:11434/v1')
  await page.getByLabel('Embedding model', { exact: true }).fill('  custom-embedding-model  ')
  await page.getByLabel('Ollama base URL', { exact: true }).fill('  http://127.0.0.1:11434/v1  ')
  await expect(page.getByText('Saved', { exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('settings-memory.png') })
  await page.getByRole('button', { name: 'Back to workspace', exact: true }).click()
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await navigation.getByRole('button', { name: 'Memory', exact: true }).click()
  await expect(toggle).toBeChecked()
  await expect(page.getByLabel('Embedding model', { exact: true })).toHaveValue('custom-embedding-model')
  await toggle.uncheck()
  await expect.poll(() => page.evaluate(() => window.anvil.settings.get())).toMatchObject({
    memoryEnabled: false, memoryEmbeddingModel: 'custom-embedding-model', ollamaBaseUrl: 'http://127.0.0.1:11434/v1'
  })
})

for (const collapsed of [false, true]) {
  test(`native settings navigation returns to the task with sidebar collapsed=${collapsed}`, async ({ page }) => {
    await page.goto(`${fixture}?scenario=output&platform=darwin`)
    const sidebar = page.getByRole('complementary', { name: 'Task sidebar', includeHidden: true })
    const workspace = page.locator('main').first()
    await expect(page.getByRole('button', { name: 'Settings', exact: true })).toBeVisible()
    if (collapsed) {
      await page.keyboard.press('Meta+b')
      await expect(sidebar).toHaveAttribute('inert', '')
    }
    const previousContent = await workspace.innerText()
    await page.evaluate(() => window.dispatchEvent(new Event('fixture:open-settings')))
    const navigation = page.getByRole('navigation', { name: 'Settings sections' })
    await expect(navigation).toBeVisible()
    await page.getByLabel('Project', { exact: true }).selectOption('project-0')
    await navigation.getByRole('button', { name: 'Memory', exact: true }).click()
    // Repeated native requests keep the selected section and its draft.
    await page.getByRole('checkbox', { name: /Enable project memory/ }).check()
    await page.evaluate(() => window.dispatchEvent(new Event('fixture:open-settings')))
    await expect(page.getByRole('checkbox', { name: /Enable project memory/ })).toBeChecked()
    await page.getByRole('button', { name: 'Back to workspace' }).click()
    await expect(workspace).toBeVisible()
    expect(await workspace.innerText()).toBe(previousContent)
    if (collapsed) await expect(sidebar).toHaveAttribute('inert', '')
    else await expect(sidebar).not.toHaveAttribute('inert', '')
  })
}

test('Escape leaves settings without dismissing the preceding task composer', async ({ page }) => {
  await page.goto(`${fixture}?platform=darwin`)
  const prompt = page.getByRole('textbox', { name: 'Task prompt' })
  await prompt.fill('Keep the draft')
  await page.keyboard.press('Meta+,')
  await expect(page.getByRole('navigation', { name: 'Settings sections' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(prompt).toBeVisible()
  await expect(prompt).toHaveValue('Keep the draft')
})

test('settings suspends native dialogs and restores their drafts', async ({ page }) => {
  await page.goto(`${fixture}?scenario=review&platform=darwin`)
  await page.getByRole('tab', { name: /^Changes/ }).click()
  await page.getByRole('button', { name: 'Open PR', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Open PR', exact: true })
  await expect(dialog).toBeVisible()
  const title = dialog.getByLabel('Title', { exact: true })
  await title.fill('Keep my PR draft')
  await page.keyboard.press('Meta+,')
  await expect(page.getByRole('navigation', { name: 'Settings sections' })).toBeVisible()
  await expect(dialog).toBeHidden()
  await page.getByRole('button', { name: 'Back to workspace', exact: true }).click()
  await expect(dialog).toBeVisible()
  await expect(title).toHaveValue('Keep my PR draft')
})

test('default provider uses the custom picker and persists the choice', async ({ page }) => {
  await page.goto('/tests/e2e/fixture/')
  await page.evaluate(() => window.settingsTest.apply({ defaultModel: 'previous-model' }))
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('navigation', { name: 'Settings sections' }).getByRole('button', { name: 'Providers', exact: true }).click()
  const trigger = page.getByRole('button', { name: 'Default agent', exact: true })
  await trigger.click()
  const picker = page.getByRole('dialog', { name: 'Choose default provider' })
  await expect(picker.getByRole('button', { name: 'Codex', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await picker.getByRole('searchbox').fill('open')
  await picker.getByRole('searchbox').press('ArrowDown')
  await page.keyboard.press('Enter')
  await expect(trigger).toHaveAccessibleDescription('OpenCode')
  await expect(trigger).toBeFocused()
  await expect(page.getByText('Saved', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => window.anvil.settings.get())).toMatchObject({ defaultAgentId: 'opencode', defaultModel: '' })
})

test('workspace settings restore appearance and persist workspace-local edits on switch', async ({ page }) => {
  await page.goto(`${fixture}?workspaces`)
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  const navigation = page.getByRole('navigation', { name: 'Settings sections' })
  await navigation.getByRole('button', { name: 'Display', exact: true }).click()
  await page.getByLabel('Font size', { exact: true }).selectOption('18')
  await expect(page.getByText('Saved', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Create test workspace' }).click()
  await navigation.getByRole('button', { name: 'Display', exact: true }).click()
  await expect(page.getByLabel('Font size', { exact: true })).toHaveValue('14')
  await expect(page.locator('html')).toHaveCSS('font-size', '16px')
  await page.getByLabel('Font size', { exact: true }).selectOption('12')
  await page.getByRole('combobox', { name: 'Test workspace', exact: true }).selectOption({ label: 'Default' })
  await navigation.getByRole('button', { name: 'Display', exact: true }).click()
  await expect(page.getByLabel('Font size', { exact: true })).toHaveValue('18')
  await page.getByRole('combobox', { name: 'Test workspace', exact: true }).selectOption({ label: 'Work' })
  await navigation.getByRole('button', { name: 'Display', exact: true }).click()
  await expect(page.getByLabel('Font size', { exact: true })).toHaveValue('12')
})

test('rapid autosaves keep latest input and failure retry across dismissal', async ({ page }) => {
  await page.goto(`${fixture}?settingsControlled`)
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  const display = () => page.getByRole('navigation', { name: 'Settings sections' }).getByRole('button', { name: 'Display', exact: true }).click()
  await display()
  const font = page.getByLabel('Font size', { exact: true })
  await font.selectOption('18')
  await font.selectOption('12')
  await expect.poll(() => page.evaluate(() => window.settingsTest.calls.length)).toBe(1)
  await page.evaluate(() => window.settingsTest.release())
  await expect.poll(() => page.evaluate(() => window.settingsTest.calls.length)).toBe(2)
  await expect(font).toHaveValue('12')
  await expect(page.getByText('Saving settings…', { exact: true })).toBeVisible()
  await expect(page.getByText('Saved', { exact: true })).toBeHidden()
  await page.keyboard.press('Escape')
  await page.evaluate(() => window.settingsTest.release(true))
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await display()
  await expect(font).toHaveValue('12')
  await expect(page.getByRole('alert')).toContainText('Could not save settings')
  await page.getByRole('button', { name: 'Retry', exact: true }).click()
  await expect.poll(() => page.evaluate(() => window.settingsTest.calls.length)).toBe(3)
  await page.evaluate(() => window.settingsTest.release())
  await expect(page.getByText('Saved', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => window.settingsTest.calls)).toEqual([{ fontSize: 18 }, { fontSize: 12 }, { fontSize: 12 }])
})

test('pending workspace autosave captures its destination before a switch', async ({ page }) => {
  await page.goto(`${fixture}?settingsControlled&workspaces`)
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('navigation', { name: 'Settings sections' }).getByRole('button', { name: 'Display', exact: true }).click()
  await page.getByLabel('Font size', { exact: true }).selectOption('18')
  await page.getByRole('button', { name: 'Create test workspace' }).click()
  await expect.poll(() => page.evaluate(() => window.settingsTest.calls.length)).toBe(1)
  await page.evaluate(() => window.settingsTest.release())
  await expect(page.getByLabel('Settings workspace')).toContainText('Work')
  await page.getByRole('navigation', { name: 'Settings sections' }).getByRole('button', { name: 'Display', exact: true }).click()
  await expect(page.getByLabel('Font size', { exact: true })).toHaveValue('14')
  await page.getByRole('combobox', { name: 'Test workspace', exact: true }).selectOption({ label: 'Default' })
  await page.getByRole('navigation', { name: 'Settings sections' }).getByRole('button', { name: 'Display', exact: true }).click()
  await expect(page.getByLabel('Font size', { exact: true })).toHaveValue('18')
  expect(await page.evaluate(() => window.settingsTest.destinations)).toEqual(['default'])
})

test('all settings sections fit narrow windows with enlarged text and no action footer', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 900, height: 600 })
  await page.goto(fixture)
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  const navigation = page.getByRole('navigation', { name: 'Settings sections' })
  await navigation.getByRole('button', { name: 'Display', exact: true }).click()
  await page.getByLabel('Font size', { exact: true }).selectOption('18')
  await expect(page.getByText('Saved', { exact: true })).toBeVisible()
  const settings = page.getByTestId('settings-page')
  await expect(settings.locator('footer')).toHaveCount(0)
  await expect(settings.getByRole('button', { name: /^(Save|Close)$/ })).toHaveCount(0)
  for (const section of ['General', 'Providers', 'Source control', 'Keyboard shortcuts', 'Memory', 'Display']) {
    await navigation.getByRole('button', { name: section, exact: true }).click()
    await expect(page.getByRole('heading', { name: section, exact: true })).toBeInViewport()
    await expect(settings.getByRole('status').filter({ hasText: /^Saved$/ })).toBeInViewport()
    expect(await settings.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath(`narrow-${section}.png`) })
  }
})

test('project removal errors remain accessible in settings content', async ({ page }) => {
  await page.goto(fixture)
  await page.evaluate(() => {
    window.anvil.projects.remove = async () => { throw new Error('Could not remove project: fixture failure.') }
  })
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('button', { name: 'Remove', exact: true }).click()
  const settings = page.getByTestId('settings-page')
  await expect(settings.locator('main').getByRole('alert')).toHaveText('Could not remove project: fixture failure.')
  await expect(settings.getByRole('button', { name: /^(Save|Close)$/ })).toHaveCount(0)
  await page.keyboard.press('Escape')
  await expect(settings).toBeHidden()
})
