import { expect, test } from '@playwright/test'

const fixture = '/tests/e2e/fixture/'

test('search filters active and settled tasks by title, project, or branch', async ({ page }) => {
  await page.goto(fixture)
  const sidebar = page.getByRole('complementary')
  await sidebar.getByRole('searchbox', { name: 'Search tasks' }).fill('polish')
  await expect(sidebar.getByRole('button', { name: 'Open task: Polish task cards', exact: true })).toBeVisible()
  await expect(sidebar.getByRole('button', { name: 'Open task: Build streaming support', exact: true })).toHaveCount(0)
  await sidebar.getByRole('searchbox').fill('Workbench')
  await expect(sidebar.getByRole('button', { name: 'Open task: Layout test task', exact: true })).toBeVisible()
  await expect(sidebar.getByRole('button', { name: 'Open task: Polish task cards', exact: true })).toHaveCount(0)
  await sidebar.getByRole('searchbox').fill('anvil/polish-task-cards')
  await expect(sidebar.getByRole('button', { name: 'Open task: Polish task cards', exact: true })).toBeVisible()
  await sidebar.getByRole('searchbox').fill('old logs')
  await expect(sidebar.getByRole('button', { name: 'Open task: Clean up old logs', exact: true })).toBeVisible()
  await sidebar.getByRole('searchbox').fill('nothing matches')
  await expect(sidebar.getByText('No matching tasks.')).toBeVisible()
  await sidebar.getByRole('button', { name: 'Clear search' }).click()
  await expect(sidebar.getByRole('button', { name: 'Open task: Build streaming support', exact: true })).toBeVisible()
})

test('project filters and opening tasks switch project context correctly', async ({ page }) => {
  await page.goto(fixture)
  const sidebar = page.getByRole('complementary')
  const filters = sidebar.getByRole('navigation', { name: 'Filter tasks by project' })
  await filters.getByRole('button', { name: 'Workbench', exact: true }).click()
  await expect(sidebar.getByRole('navigation', { name: 'Active tasks' }).getByRole('article')).toHaveCount(2)
  await expect(sidebar.getByRole('button', { name: 'Open task: Polish task cards', exact: true })).toHaveCount(0)
  await filters.getByRole('button', { name: 'All', exact: true }).click()
  await sidebar.getByRole('button', { name: 'Open task: Polish task cards', exact: true }).click()
  await expect(page.getByRole('main').getByText('/tmp/anvil', { exact: true })).toBeVisible()
  await sidebar.getByRole('button', { name: 'Open task: Layout test task', exact: true }).click()
  await expect(page.getByRole('main').getByText('/tmp/workbench', { exact: true })).toBeVisible()
})

test('hover settling moves reviewed work into the bottom accordion without closing it', async ({ page }) => {
  await page.goto(fixture)
  const sidebar = page.getByRole('complementary')
  const tasks = sidebar.getByRole('navigation', { name: 'Active tasks' })
  const task = tasks.getByRole('button', { name: 'Open task: Polish task cards', exact: true })
  await task.click()
  await task.hover()
  await tasks.getByRole('button', { name: 'Settle task: Polish task cards', exact: true }).click()
  await expect(task).toHaveCount(0)
  await expect(page.getByRole('main').getByRole('heading', { name: 'Polish task cards' })).toBeVisible()
  const settled = sidebar.getByRole('region', { name: 'Settled tasks' })
  const toggle = settled.getByRole('button', { name: /^Settled/ })
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  await toggle.click()
  await expect(settled.getByRole('button', { name: 'Open task: Polish task cards', exact: true })).toBeVisible()
  await expect(settled.getByRole('button', { name: 'Open task: Clean up old logs', exact: true })).toBeVisible()
  await toggle.click()
  await expect(settled.getByRole('button', { name: 'Open task: Polish task cards', exact: true })).toHaveCount(0)
  await expect(tasks.getByRole('button', { name: /^Settle task: (Build streaming support|Review sidebar changes|Retry provider setup)$/ })).toHaveCount(0)
})

test('settlement failure preserves the task and reports an error', async ({ page }) => {
  await page.goto(`${fixture}?settleFailure=1`)
  const task = page.getByRole('button', { name: 'Open task: Polish task cards', exact: true })
  await task.hover()
  await page.getByRole('button', { name: 'Settle task: Polish task cards', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveText('Settlement failed for testing')
  await expect(task).toBeVisible()
})

test('Settings is a seamless icon row and stays reachable in a short window', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 900, height: 500 })
  await page.goto(fixture)
  const settings = page.getByRole('complementary').getByRole('button', { name: 'Settings', exact: true })
  await expect(settings).toBeInViewport()
  await expect(settings).toHaveCSS('border-top-width', '0px')
  await expect(settings.locator('svg')).toHaveCount(1)
  await page.screenshot({ path: testInfo.outputPath('sidebar.png') })
  await settings.click()
  await expect(page.getByRole('heading', { name: 'Settings', exact: true })).toBeVisible()
})
