import { expect, test } from '@playwright/test'

const fixture = '/tests/e2e/fixture/'

test('task status icons and highlights remain visible when selected, hovered, and settled', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1100, height: 900 })
  await page.goto(fixture)
  const sidebar = page.getByRole('complementary')
  const merged = sidebar.getByRole('button', { name: 'Open task: Polish task cards', exact: true })
  const review = sidebar.getByRole('button', { name: 'Open task: Review sidebar changes', exact: true })
  const failed = sidebar.getByRole('button', { name: 'Open task: Retry provider setup', exact: true })
  await expect(merged.getByRole('img', { name: 'Merged', exact: true })).toHaveCSS('color', 'rgb(187, 154, 247)')
  await expect(review.getByRole('img', { name: 'Ready for review', exact: true })).toHaveClass(/text-orange-400/)
  await expect(failed.getByRole('img', { name: 'Failed', exact: true })).toHaveCSS('color', 'rgb(224, 108, 117)')
  await expect(merged.locator('..')).toHaveClass(/bg-violet\/8/)
  await expect(review.locator('..')).toHaveClass(/bg-orange-400\/8/)
  await merged.click()
  await merged.hover()
  await expect(merged.getByRole('img', { name: 'Merged', exact: true })).toBeVisible()
  await expect(merged.locator('..')).toHaveClass(/bg-violet\/8/)
  await expect(merged.locator('..')).toHaveClass(/outline-offset-1/)
  await page.screenshot({ path: testInfo.outputPath('sidebar-task-statuses.png') })
  await sidebar.getByRole('button', { name: 'Settle task: Polish task cards', exact: true }).click()
  const settled = sidebar.getByRole('region', { name: 'Settled tasks' })
  await settled.getByRole('button', { name: /^Settled/ }).click()
  const settledTask = settled.getByRole('button', { name: 'Open task: Polish task cards', exact: true })
  await expect(settledTask.getByRole('img', { name: 'Merged', exact: true })).toBeVisible()
  await expect(settledTask.locator('..')).toHaveClass(/bg-violet\/8/)
})

test('task updates replace the sidebar status without leaving stale success indicators', async ({ page }) => {
  await page.goto(fixture)
  const task = page.getByRole('button', { name: 'Open task: Build streaming support', exact: true })
  const scenarios = [
    { status: 'succeeded', deliveryStatus: 'reviewable', hasPullRequest: false, label: 'Ready for review' },
    { status: 'succeeded', deliveryStatus: 'reviewable', hasPullRequest: true, label: 'Open PR' },
    { status: 'succeeded', deliveryStatus: 'approved', hasPullRequest: true, label: 'Merged' },
    { status: 'running', deliveryStatus: 'approved', hasPullRequest: true, label: 'Working' },
    { status: 'failed', deliveryStatus: 'reviewable', hasPullRequest: true, label: 'Failed' },
    { status: 'succeeded', deliveryStatus: 'failed', hasPullRequest: false, label: 'Failed' },
    { status: 'cancelled', deliveryStatus: 'approved', hasPullRequest: false, label: null },
    { status: 'succeeded', deliveryStatus: 'no_changes', hasPullRequest: false, label: 'Done' }
  ] as const
  await expect(task.getByRole('img', { name: 'Working', exact: true })).toBeVisible()
  for (const scenario of scenarios) {
    await page.evaluate(async ({ status, deliveryStatus, hasPullRequest }) => {
      const current = (await window.anvil.tasks.list()).find((task) => task.id === 'running')!
      window.dispatchEvent(new CustomEvent('fixture:task-updated', { detail: {
        ...current, status, deliveryStatus,
        pullRequest: hasPullRequest ? { number: 42, url: 'https://github.com/developer/anvil/pull/42' } : undefined
      } }))
    }, scenario)
    if (scenario.label) {
      await expect(task.getByRole('img', { name: scenario.label, exact: true })).toBeVisible()
      await expect(task.getByRole('img')).toHaveCount(1)
    } else {
      await expect(task.getByRole('img')).toHaveCount(0)
    }
    if (scenario.label === 'Open PR') {
      await expect(task.getByRole('img', { name: 'Open PR', exact: true }).locator('path')).toHaveAttribute('d', /M15 6C12\.6131/)
      await expect(task.locator('..')).toHaveClass(/bg-ok\/8/)
    } else if (scenario.label === 'Merged') {
      await expect(task.locator('..')).toHaveClass(/bg-violet\/8/)
    } else if (scenario.label !== 'Ready for review') {
      await expect(task.locator('..')).not.toHaveClass(/bg-(ok|orange-400|violet)\/8/)
    }
  }
})

test('search filters active and settled tasks by title, project, or branch', async ({ page }) => {
  await page.goto(fixture)
  const sidebar = page.getByRole('complementary')
  await sidebar.getByRole('searchbox', { name: 'Search tasks' }).fill('polish')
  await expect(sidebar.getByRole('button', { name: 'Open task: Polish task cards', exact: true })).toBeVisible()
  await expect(sidebar.getByRole('button', { name: 'Open task: Build streaming support', exact: true })).toHaveCount(0)
  await sidebar.getByRole('searchbox').fill('Workbench')
  await expect(sidebar.getByRole('button', { name: 'Open task: Layout test task', exact: true })).toBeVisible()
  await expect(sidebar.getByRole('button', { name: 'Open task: Polish task cards', exact: true })).toHaveCount(0)
  await sidebar.getByRole('searchbox').fill('anvil/polish-task-cards')
  await expect(sidebar.getByRole('button', { name: 'Open task: Polish task cards', exact: true })).toBeVisible()
  await sidebar.getByRole('searchbox').fill('old logs')
  await expect(sidebar.getByRole('button', { name: 'Open task: Clean up old logs', exact: true })).toBeVisible()
  await sidebar.getByRole('searchbox').fill('nothing matches')
  await expect(sidebar.getByText('No matching tasks.')).toBeVisible()
  await sidebar.getByRole('button', { name: 'Clear search' }).click()
  await expect(sidebar.getByRole('button', { name: 'Open task: Build streaming support', exact: true })).toBeVisible()
})

test('project filters and opening tasks switch project context correctly', async ({ page }) => {
  await page.goto(fixture)
  const sidebar = page.getByRole('complementary')
  const selector = sidebar.getByRole('combobox', { name: 'Project', exact: true })
  await selector.click()
  await sidebar.getByRole('option').filter({ hasText: '/tmp/workbench' }).click()
  await expect(sidebar.getByRole('navigation', { name: 'Active tasks' }).getByRole('article')).toHaveCount(2)
  await expect(sidebar.getByRole('button', { name: 'Open task: Polish task cards', exact: true })).toHaveCount(0)
  await selector.click()
  await sidebar.getByRole('option', { name: 'All Tasks from all projects', exact: true }).click()
  await sidebar.getByRole('button', { name: 'Open task: Polish task cards', exact: true }).click()
  await expect(page.getByRole('main').getByText('Anvil', { exact: true })).toBeVisible()
  await sidebar.getByRole('button', { name: 'Open task: Layout test task', exact: true }).click()
  await expect(page.getByRole('main').getByText('Workbench', { exact: true })).toBeVisible()
})

test('hover settling moves reviewed work into the bottom accordion without closing it', async ({ page }) => {
  await page.goto(fixture)
  const sidebar = page.getByRole('complementary')
  const tasks = sidebar.getByRole('navigation', { name: 'Active tasks' })
  const task = tasks.getByRole('button', { name: 'Open task: Polish task cards', exact: true })
  await task.click()
  await task.hover()
  await tasks.getByRole('button', { name: 'Settle task: Polish task cards', exact: true }).click()
  await expect(task).toHaveCount(0)
  await expect(page.getByRole('main').getByRole('heading', { name: 'Polish task cards' })).toBeVisible()
  const settled = sidebar.getByRole('region', { name: 'Settled tasks' })
  const toggle = settled.getByRole('button', { name: /^Settled/ })
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  await toggle.click()
  await expect(settled.getByRole('button', { name: 'Open task: Polish task cards', exact: true })).toBeVisible()
  await expect(settled.getByRole('button', { name: 'Open task: Clean up old logs', exact: true })).toBeVisible()
  await toggle.click()
  await expect(settled.getByRole('button', { name: 'Open task: Polish task cards', exact: true })).toHaveCount(0)
  await expect(tasks.getByRole('button', { name: /^Settle task: (Build streaming support|Review sidebar changes|Retry provider setup)$/ })).toHaveCount(0)
})

test('settlement failure preserves the task and reports an error', async ({ page }) => {
  await page.goto(`${fixture}?settleFailure=1`)
  const task = page.getByRole('button', { name: 'Open task: Polish task cards', exact: true })
  await task.hover()
  await page.getByRole('button', { name: 'Settle task: Polish task cards', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveText('Settlement failed for testing')
  await expect(task).toBeVisible()
})

test('Settings is a seamless icon row and stays reachable in a short window', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 900, height: 500 })
  await page.goto(fixture)
  const settings = page.getByRole('complementary').getByRole('button', { name: 'Settings', exact: true })
  await expect(settings).toBeInViewport()
  await expect(settings).toHaveCSS('border-top-width', '0px')
  await expect(settings.locator('svg')).toHaveCount(1)
  await page.screenshot({ path: testInfo.outputPath('sidebar.png') })
  await settings.click()
  await expect(page.getByRole('heading', { name: 'Settings', exact: true })).toBeVisible()
})

test('project selection keeps All separate from composer context and survives settings', async ({ page }) => {
  await page.goto(fixture)
  const selector = page.getByRole('combobox', { name: 'Project', exact: true })
  const sidebar = page.getByRole('complementary', { name: 'Task sidebar' })
  await selector.fill('WORKBENCH')
  await expect(page.getByRole('listbox', { name: 'Projects' }).getByRole('option')).toHaveCount(1)
  await selector.press('Enter')
  await expect(selector).toHaveValue('Workbench')
  await expect(page.getByTestId('composer-project-name')).toHaveText('Workbench')
  const branch = page.getByRole('button', { name: 'Project branch', exact: true })
  await branch.click()
  await page.getByRole('dialog', { name: 'Choose branch' }).getByRole('button', { name: 'feature/composer', exact: true }).click()
  await expect(branch).toHaveAccessibleDescription('feature/composer')
  await selector.click()
  await expect(page.getByRole('listbox', { name: 'Projects' }).getByRole('option', { selected: true })).toContainText('/tmp/workbench')
  await selector.press('Home')
  await selector.press('Enter')
  await expect(selector).toHaveValue('All')
  await expect(page.getByTestId('composer-project-name')).toHaveText('Workbench')
  await expect(branch).toHaveAccessibleDescription('feature/composer')
  await expect(sidebar.getByRole('navigation', { name: 'Active tasks' }).getByRole('article')).toHaveCount(5)
  await selector.fill('workbench')
  await selector.press('Enter')
  await sidebar.getByRole('searchbox', { name: 'Search tasks' }).fill('layout')
  await sidebar.getByRole('button', { name: 'Settings', exact: true }).click()
  await expect(sidebar).toHaveCount(0)
  await expect(page.getByRole('navigation', { name: 'Settings sections' }).getByRole('button')).toHaveCount(6)
  await page.getByRole('button', { name: 'Back to workspace', exact: true }).click()
  await expect(selector).toHaveValue('Workbench')
  await expect(sidebar.getByRole('searchbox', { name: 'Search tasks' })).toHaveValue('layout')
  await expect(sidebar.getByRole('navigation', { name: 'Active tasks' }).getByRole('article')).toHaveCount(1)
  await expect(page.getByTestId('composer-project-name')).toHaveText('Workbench')
})

test('project input supports keyboard-only selection, cancellation and no matches', async ({ page }) => {
  await page.goto(fixture)
  const taskSearch = page.getByRole('searchbox', { name: 'Search tasks' })
  await taskSearch.focus()
  await page.keyboard.press('Shift+Tab')
  await expect(page.getByRole('button', { name: 'New task', exact: true })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(taskSearch).toBeFocused()
  await page.keyboard.press('Tab')
  const selector = page.getByRole('combobox', { name: 'Project', exact: true })
  await expect(selector).toBeFocused()
  await expect(selector).toHaveAttribute('aria-expanded', 'true')
  await selector.press('End')
  await selector.press('ArrowUp')
  await selector.press('ArrowDown')
  await selector.press('Enter')
  await expect(selector).toHaveValue('Workbench')
  await expect(selector).toBeFocused()
  await selector.press('ArrowDown')
  await selector.fill('missing-repository')
  await expect(page.getByRole('status')).toHaveText('No projects match your search.')
  await expect(selector).not.toHaveAttribute('aria-activedescendant')
  await selector.press('Enter')
  await expect(page.getByRole('listbox', { name: 'Projects' })).toBeVisible()
  await selector.press('Escape')
  await expect(selector).toHaveValue('Workbench')
  await expect(selector).toHaveAttribute('aria-expanded', 'false')
  await selector.press('Enter')
  await selector.fill('anvil')
  await selector.press('Tab')
  await expect(page.getByRole('button', { name: 'Add project', exact: true })).toBeFocused()
  await expect(selector).toHaveValue('Workbench')
  await selector.click()
  await taskSearch.click()
  await expect(selector).toHaveAttribute('aria-expanded', 'false')
})

test('large project lists distinguish duplicate names by path without horizontal overflow', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 600, height: 700 })
  await page.goto(fixture + '?manyProjects')
  const sidebar = page.getByRole('complementary', { name: 'Task sidebar' })
  const selector = sidebar.getByRole('combobox', { name: 'Project', exact: true })
  await selector.fill('duplicate')
  await expect(page.getByRole('listbox', { name: 'Projects' }).getByRole('option')).toHaveCount(2)
  const paths = await page.getByRole('listbox', { name: 'Projects' }).getByRole('option').allTextContents()
  expect(paths[0]).toContain('repository-0')
  expect(paths[1]).toContain('repository-1')
  await selector.press('ArrowDown')
  await selector.press('Enter')
  await expect(selector).toHaveValue('Duplicate')
  await expect(selector).toHaveAttribute('title', /repository-1$/)
  await expect(page.getByTestId('composer-project-name')).toHaveText('Duplicate')
  await selector.fill('repository-149')
  await expect(page.getByRole('listbox', { name: 'Projects' }).getByRole('option')).toHaveCount(1)
  await selector.press('Enter')
  await expect(selector).toHaveValue('Project 149')
  await selector.click()
  const list = page.getByRole('listbox', { name: 'Projects' })
  await expect(page.getByRole('listbox', { name: 'Projects' }).getByRole('option')).toHaveCount(153)
  await expect(page.getByRole('listbox', { name: 'Projects' }).getByRole('option', { selected: true })).toBeInViewport()
  expect(await list.evaluate((el) => el.scrollHeight > el.clientHeight && el.scrollWidth === el.clientWidth)).toBe(true)
  expect(await sidebar.evaluate((el) => el.scrollWidth === el.clientWidth)).toBe(true)
  await expect(sidebar.getByRole('navigation', { name: 'Filter tasks by project' })).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('sidebar-project-selector-narrow.png') })
  await selector.press('Home')
  await expect(page.getByRole('listbox', { name: 'Projects' }).getByRole('option').first()).toBeInViewport()
  await selector.press('End')
  await expect(page.getByRole('listbox', { name: 'Projects' }).getByRole('option').last()).toBeInViewport()
})

test('adding and removing projects restores a valid filter and composer project', async ({ page }) => {
  await page.goto(fixture)
  const selector = page.getByRole('combobox', { name: 'Project', exact: true })
  await selector.fill('workbench')
  await selector.press('Enter')
  await page.getByRole('button', { name: 'Add project', exact: true }).click()
  await expect(selector).toHaveValue('New project')
  await expect(page.getByTestId('composer-project-name')).toHaveText('New project')
  await expect(page.getByText('No tasks yet.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('button', { name: 'Remove', exact: true }).click()
  await expect(selector).toHaveValue('All')
  await expect(page.getByTestId('composer-project-name')).toHaveText('Anvil')
  await expect(page.getByRole('button', { name: 'Project branch', exact: true })).toHaveAccessibleDescription('main')
  await selector.fill('workbench')
  await selector.press('Enter')
  await selector.fill('workbench')
  await page.evaluate(() => window.dispatchEvent(new CustomEvent('fixture:remove-project', { detail: 'project-1' })))
  await expect(selector).toHaveValue('All')
  await expect(selector).toHaveAttribute('aria-expanded', 'false')
  await expect(page.getByTestId('composer-project-name')).toHaveText('Anvil')
  await selector.click()
  await expect(page.getByRole('listbox', { name: 'Projects' }).getByRole('option')).toHaveCount(2)
  await expect(page.getByRole('listbox', { name: 'Projects' }).getByRole('option', { selected: true })).toContainText('All')
})

test('empty projects offer All and Add project, including after the last removal', async ({ page }) => {
  await page.goto(fixture + '?noProjects')
  const selector = page.getByRole('combobox', { name: 'Project', exact: true })
  const newTask = page.getByRole('button', { name: 'New task', exact: true })
  await expect(newTask).toBeDisabled()
  await selector.click()
  await expect(page.getByRole('status')).toHaveText('No projects yet. Use Add project to get started.')
  await expect(page.getByRole('listbox', { name: 'Projects' }).getByRole('option', { selected: true })).toContainText('All')
  await selector.press('Escape')
  await page.getByRole('button', { name: 'Add project', exact: true }).click()
  await expect(newTask).toBeEnabled()
  await expect(selector).toHaveValue('New project')
  await expect(page.getByTestId('composer-project-name')).toHaveText('New project')
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('button', { name: 'Remove', exact: true }).click()
  await expect(selector).toHaveValue('All')
  await expect(newTask).toBeDisabled()
  await expect(page.getByTestId('composer-project-name')).toHaveCount(0)
  await selector.click()
  await expect(page.getByRole('status')).toContainText('No projects yet.')
})
