import { expect, test } from '@playwright/test'

test('task usage shows cached input and explains cumulative request totals', async ({ page }, testInfo) => {
  await page.goto('/tests/e2e/fixture/?scenario=output&taskUsage=1')
  const main = page.getByRole('main')
  const cached = main.locator('[title="638.2K cached input"]')
  await expect(cached.getByText('Cached', { exact: true })).toBeVisible()
  await expect(cached.getByText('638.2K', { exact: true })).toBeVisible()
  await expect(main.getByText(/^688\.8K\s*in$/)).toBeVisible()
  await expect(main.getByText(/^3\.6K\s*out$/)).toBeVisible()
  const tokens = main.locator('[title*="688,809 input"]')
  await expect(tokens).toHaveAttribute('title', /50,601 uncached/)
  await expect(tokens).toHaveAttribute('title', /across model requests/)
  await page.screenshot({ path: testInfo.outputPath('task-usage.png') })
})

test('context occupancy appears beside billing and compact is disabled during coding', async ({ page }, testInfo) => {
  await page.goto('/tests/e2e/fixture/?scenario=output&taskUsage=1&contextUsage=1')
  const stat = page.getByRole('main').locator('[title*="in the current session"]')
  await expect(stat).toContainText('Context')
  await expect(stat).toContainText('67%')
  await expect(stat).toHaveAttribute('title', /142K \/ 213K/)
  await expect(page.getByRole('button', { name: 'Compact', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Compact', exact: true }).click()
  await page.screenshot({ path: testInfo.outputPath('task-context.png') })
  await page.goto('/tests/e2e/fixture/?scenario=output&contextUsage=1&steering=1&running=1')
  await expect(page.getByRole('button', { name: 'Compact', exact: true })).toBeDisabled()
  await page.goto('/tests/e2e/fixture/?scenario=output')
  await expect(page.getByRole('main').locator('[title*="in the current session"]')).toHaveCount(0)
})

test('workspace context settings default to 75 percent and save changes', async ({ page }, testInfo) => {
  await page.goto('/tests/e2e/fixture/')
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('navigation', { name: 'Settings sections' }).getByRole('button', { name: 'Providers', exact: true }).click()
  const toggle = page.getByLabel('Auto-compact task context')
  const threshold = page.getByLabel('Context threshold (%)')
  await expect(toggle).toBeChecked()
  await expect(threshold).toHaveValue('75')
  await threshold.fill('85')
  await toggle.uncheck()
  await expect(threshold).toBeDisabled()
  await page.screenshot({ path: testInfo.outputPath('context-settings.png') })
  await toggle.check()
  await expect(threshold).toHaveValue('85')
})
