import { expect, test, type Page } from '@playwright/test'
import { chooseProvider } from './composer-setup'

const fixture = '/tests/e2e/fixture/'
const picker = (page: Page) => page.getByRole('combobox', { name: 'Workspace', exact: true })

async function selectWorkspace(page: Page, name: string): Promise<void> {
  await picker(page).fill(name)
  await page.getByRole('listbox', { name: 'Workspaces' }).getByRole('option').filter({ hasText: name }).click()
  await expect(picker(page)).toHaveValue(name)
  await expect(picker(page)).toBeFocused()
}

async function createWorkspace(page: Page, name: string): Promise<void> {
  await picker(page).click()
  await page.getByRole('button', { name: 'Create workspace', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Create workspace', exact: true })
  await dialog.getByRole('textbox', { name: 'Workspace name' }).fill(name)
  await dialog.getByRole('button', { name: 'Create workspace', exact: true }).click()
  await expect(page.getByLabel('Settings workspace', { exact: true })).toHaveText(`Workspace: ${name}`)
  await expect(page.getByRole('region', { name: `Codex account for ${name}`, exact: true }).getByRole('status')).toHaveText('Signed out')
  await expect(page.getByRole('region', { name: `OpenCode account for ${name}`, exact: true }).getByRole('status')).toHaveText('Signed out')
}

async function back(page: Page): Promise<void> {
  await page.getByRole('button', { name: 'Back to workspace', exact: true }).click()
}

test('Workspace is below Settings and supports keyboard selection, filtering and focus restoration', async ({ page }, testInfo) => {
  await page.goto(fixture)
  await createWorkspace(page, 'Work')
  await back(page)
  const settings = page.getByRole('button', { name: 'Settings', exact: true })
  const settingsBox = (await settings.boundingBox())!
  const workspaceBox = (await picker(page).boundingBox())!
  expect(workspaceBox.y).toBeGreaterThan(settingsBox.y + settingsBox.height)
  await settings.focus()
  await page.keyboard.press('Tab')
  await expect(picker(page)).toBeFocused()
  await expect(page.getByRole('listbox', { name: 'Workspaces' }).getByRole('option', { selected: true })).toHaveText('WorkSelected workspace')
  await expect(page.getByRole('listbox', { name: 'Workspaces' }).getByRole('option')).toHaveCount(2)
  await picker(page).press('Home')
  await picker(page).press('ArrowDown')
  await picker(page).press('ArrowUp')
  await picker(page).press('Enter')
  await expect(picker(page)).toHaveValue('Default')
  await expect(picker(page)).toBeFocused()
  await expect(picker(page)).toHaveAccessibleDescription('Selected workspace: Default')
  await picker(page).fill('missing-profile')
  await expect(page.getByText('No workspaces match your search.', { exact: true })).toBeVisible()
  await expect(picker(page)).not.toHaveAttribute('aria-activedescendant')
  await picker(page).press('Enter')
  await expect(picker(page)).toHaveAttribute('aria-expanded', 'true')
  await picker(page).press('Escape')
  await expect(picker(page)).toHaveValue('Default')
  await picker(page).press('Enter')
  await picker(page).press('End')
  await picker(page).press('Enter')
  await expect(picker(page)).toHaveValue('Work')
  await picker(page).click()
  await page.screenshot({ path: testInfo.outputPath('workspace-selector.png') })
  await page.getByRole('searchbox', { name: 'Search tasks' }).click()
  await expect(picker(page)).toHaveAttribute('aria-expanded', 'false')
})

test('create and rename validate names, trap focus, prevent duplicates and preserve stable IDs', async ({ page }) => {
  await page.goto(fixture + '?workspaceDelay')
  await picker(page).focus()
  await picker(page).press('Tab')
  await expect(page.getByRole('button', { name: 'Create workspace', exact: true })).toBeFocused()
  await page.keyboard.press('Enter')
  const dialog = page.getByRole('dialog', { name: 'Create workspace', exact: true })
  const name = dialog.getByRole('textbox', { name: 'Workspace name' })
  await expect(name).toBeFocused()
  await expect(dialog).toContainText('Start with default settings and signed-out agents.')
  await name.press('Enter')
  await expect(dialog.getByRole('alert')).toHaveText('Enter a workspace name.')
  await name.fill('  DEFAULT  ')
  await name.press('Enter')
  await expect(name).toHaveAttribute('aria-invalid', 'true')
  await expect(dialog.getByRole('alert')).toHaveText('A workspace with that name already exists.')
  await name.fill('x'.repeat(81))
  await name.press('Enter')
  await expect(dialog.getByRole('alert')).toContainText('Use up to 80 characters')
  await name.fill('  Work  ')
  await name.press('Enter')
  await page.keyboard.press('Enter')
  await expect(dialog.getByRole('button', { name: 'Saving…' })).toBeDisabled()
  await expect(page.getByLabel('Settings workspace')).toHaveText('Workspace: Work')
  const created = await page.evaluate(() => window.anvil.workspaces.list())
  expect(created).toHaveLength(2)
  const workId = created.find((workspace) => workspace.name === 'Work')!.id
  await back(page)
  await picker(page).click()
  await page.getByRole('button', { name: 'Rename workspace', exact: true }).click()
  const rename = page.getByRole('dialog', { name: 'Rename workspace', exact: true })
  await rename.getByRole('textbox').fill('Personal')
  await rename.getByRole('button', { name: 'Save name', exact: true }).click()
  await expect(picker(page)).toHaveValue('Personal')
  await expect(picker(page)).toBeFocused()
  expect((await page.evaluate(() => window.anvil.workspaces.list())).find((workspace) => workspace.id === workId)?.name).toBe('Personal')
  await picker(page).click()
  await page.getByRole('button', { name: 'Rename workspace', exact: true }).click()
  await page.keyboard.press('Shift+Tab')
  await expect(page.getByRole('button', { name: 'Save name', exact: true })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(picker(page)).toBeFocused()
  await expect(picker(page)).toHaveValue('Personal')
})

test('switching restores project, preferences and history while background tasks retain their owner', async ({ page }) => {
  await page.goto(fixture)
  const composer = page.getByRole('form', { name: 'Start a task' })
  await chooseProvider(composer.getByRole('button', { name: /^(Choose a model|Model:)/ }), 'codex', 'gpt-5-mini')
  await page.getByRole('combobox', { name: 'Project', exact: true }).fill('workbench')
  await page.keyboard.press('Enter')
  await composer.getByRole('textbox').fill('Private draft')
  await page.getByRole('searchbox').fill('layout')
  await createWorkspace(page, 'Work')
  await page.getByRole('button', { name: 'Display', exact: true }).click()
  await expect(page.getByLabel('Font size', { exact: true })).toHaveValue('14')
  await page.getByLabel('Font size', { exact: true }).selectOption('16')
  await page.getByRole('button', { name: 'Save', exact: true }).click()
  await expect(page.getByText('Saved', { exact: true })).toBeVisible()
  await back(page)
  await expect(page.getByRole('searchbox')).toHaveValue('')
  await expect(page.getByRole('combobox', { name: 'Project', exact: true })).toHaveValue('All')
  await expect(composer.getByRole('textbox')).toHaveValue('')
  await expect(composer.getByRole('button', { name: 'Choose a model', exact: true })).toBeVisible()
  await expect(page.getByText('No tasks yet.', { exact: true })).toBeVisible()
  await expect(page.getByTestId('composer-project-name')).toHaveText('Anvil')
  // An update from the background profile must not appear in this profile.
  await page.evaluate(async () => {
    const running = (await window.anvil.tasks.list()).find((task) => task.id === 'running')!
    window.dispatchEvent(new CustomEvent('fixture:task-updated', { detail: { ...running, title: 'Background work continues' } }))
  })
  await expect(page.getByRole('button', { name: 'Open task: Background work continues', exact: true })).toHaveCount(0)
  await selectWorkspace(page, 'Default')
  await expect(page.getByTestId('composer-project-name')).toHaveText('Workbench')
  await expect(composer.getByRole('button', { name: 'Model: GPT 5 Mini', exact: true })).toBeVisible()
  await expect(composer.getByRole('textbox')).toHaveValue('')
  await page.getByRole('button', { name: 'Open task: Background work continues', exact: true }).click()
  await expect(page.getByLabel('Task workspace', { exact: true })).toHaveText('Default')
  await page.getByRole('button', { name: 'Open task: Review sidebar changes', exact: true }).click()
  await expect(page.getByLabel('Task workspace', { exact: true })).toHaveText('Default')
  await selectWorkspace(page, 'Work')
  await page.reload()
  await expect(picker(page)).toHaveValue('Work')
  await expect(page.getByTestId('composer-project-name')).toHaveText('Anvil')
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('button', { name: 'Display', exact: true }).click()
  await expect(page.getByLabel('Font size', { exact: true })).toHaveValue('16')
})

for (const operation of ['Create', 'Rename']) {
  test(`${operation} errors remain inline and allow cancellation`, async ({ page }) => {
    await page.goto(`${fixture}?workspace${operation}Failure`)
    await picker(page).click()
    await page.getByRole('button', { name: `${operation} workspace`, exact: true }).click()
    const dialog = page.getByRole('dialog', { name: `${operation} workspace`, exact: true })
    await dialog.getByRole('textbox').fill('Work')
    await dialog.getByRole('button', { name: operation === 'Create' ? 'Create workspace' : 'Save name', exact: true }).click()
    await expect(dialog.getByRole('alert')).toHaveText(`Could not ${operation.toLowerCase()} workspace. Try again.`)
    await expect(dialog.getByRole('textbox')).toBeEnabled()
    await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
    await expect(picker(page)).toHaveValue('Default')
    await expect(picker(page)).toBeFocused()
  })
}

test('switch failures retain one coherent selected workspace and can be retried', async ({ page }) => {
  await page.goto(fixture + '?workspaceSelectFailure&workspaceDelay')
  await page.evaluate(() => window.anvil.workspaces.create('Work'))
  await page.reload()
  await picker(page).fill('Work')
  await picker(page).press('Enter')
  await expect(page.getByRole('alert')).toContainText('Could not switch workspace. Try again.')
  await expect(picker(page)).toHaveValue('Default')
  await expect(picker(page)).toBeFocused()
  await picker(page).click()
  await expect(page.getByRole('listbox', { name: 'Workspaces' }).getByRole('option', { selected: true })).toHaveText('DefaultSelected workspace')
  await picker(page).press('Escape')
  await page.getByRole('button', { name: 'Retry workspace' }).click()
  await expect(page.getByRole('alert')).toHaveCount(0)
})

test('long names fit small windows and collapsed sidebar is absent from keyboard navigation', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 600, height: 500 })
  await page.goto(fixture)
  const longName = 'Work '.repeat(15).trim()
  await createWorkspace(page, longName)
  await back(page)
  await picker(page).click()
  const sidebar = page.getByRole('complementary', { name: 'Task sidebar' })
  await expect(picker(page)).toBeInViewport()
  await expect(page.getByRole('listbox', { name: 'Workspaces' })).toBeInViewport()
  expect(await sidebar.evaluate((element) => element.scrollWidth === element.clientWidth)).toBe(true)
  await expect(page.getByRole('listbox', { name: 'Workspaces' }).getByRole('option', { selected: true })).toHaveAttribute('title', longName)
  await page.screenshot({ path: testInfo.outputPath('workspace-small-window.png') })
  await picker(page).press('Escape')
  await page.keyboard.press('Control+b')
  await expect(picker(page)).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('workspace-collapsed.png') })
  await page.keyboard.press('Control+b')
  await expect(picker(page)).toHaveValue(longName)
  await expect(picker(page)).toHaveAttribute('aria-expanded', 'false')
})

test('Escape closes workspace actions and restores combobox focus', async ({ page }) => {
  await page.goto(fixture)
  await picker(page).focus()
  await picker(page).press('Tab')
  await expect(page.getByRole('button', { name: 'Create workspace', exact: true })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(picker(page)).toBeFocused()
  await expect(picker(page)).toHaveAttribute('aria-expanded', 'false')
})

test('rapid queued selections end with one workspace and its own settings', async ({ page }) => {
  await page.goto(fixture + '?workspaceDelay')
  await page.getByRole('combobox', { name: 'Project', exact: true }).fill('workbench')
  await page.evaluate(async () => {
    const work = await window.anvil.workspaces.create('Work')
    const personal = await window.anvil.workspaces.create('Personal')
    await window.anvil.settings.set(work.id, { fontSize: 18 })
    await Promise.all([
      window.workspaceTest.select(work.id),
      window.workspaceTest.select('default'),
      window.workspaceTest.select(personal.id)
    ])
  })
  await expect(picker(page)).toHaveValue('Personal')
  await expect(page.getByRole('combobox', { name: 'Project', exact: true })).toHaveValue('All')
  await expect(page.getByRole('combobox', { name: 'Project', exact: true })).toHaveAttribute('aria-expanded', 'false')
  expect((await page.evaluate(() => window.anvil.workspaces.snapshot())).workspace.name).toBe('Personal')
  await expect(page.getByText('No tasks yet.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Settings', exact: true }).click()
  await page.getByRole('button', { name: 'Display', exact: true }).click()
  await expect(page.getByLabel('Font size', { exact: true })).toHaveValue('14')
})
